
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});null;
e.onRuntimeInitialized=function(){function a(g,l){this.Ra=g;this.db=l;this.Pa=1;this.lb=[]}function b(g,l){this.db=l;l=ea(g)+1;this.eb=fa(l);if(null===this.eb)throw Error("Unable to allocate memory for the SQL string");k(g,n,this.eb,l);this.jb=this.eb;this.$a=this.pb=null}function c(g){this.filename="dbfile_"+(4294967295*Math.random()>>>0);if(null!=g){var l=this.filename,p=l?r("//"+l):"/";l=ha(!0,!0);p=ia(p,(void 0!==l?l:438)&4095|32768,0);if(g){if("string"===typeof g){for(var q=Array(g.length),w=
0,O=g.length;w<O;++w)q[w]=g.charCodeAt(w);g=q}ja(p,l|146);q=v(p,577);la(q,g,0,g.length,0,void 0);ma(q);ja(p,l)}}this.handleError(h(this.filename,d));this.db=y(d,"i32");jc(this.db);this.fb={};this.Ya={}}var d=z(4),f=e.cwrap,h=f("sqlite3_open","number",["string","number"]),m=f("sqlite3_close_v2","number",["number"]),t=f("sqlite3_exec","number",["number","string","number","number","number"]),x=f("sqlite3_changes","number",["number"]),u=f("sqlite3_prepare_v2","number",["number","string","number","number",
"number"]),C=f("sqlite3_sql","string",["number"]),J=f("sqlite3_normalized_sql","string",["number"]),ca=f("sqlite3_prepare_v2","number",["number","number","number","number","number"]),kc=f("sqlite3_bind_text","number",["number","number","number","number","number"]),ub=f("sqlite3_bind_blob","number",["number","number","number","number","number"]),lc=f("sqlite3_bind_double","number",["number","number","number"]),mc=f("sqlite3_bind_int","number",["number","number","number"]),nc=f("sqlite3_bind_parameter_index",
"number",["number","string"]),oc=f("sqlite3_step","number",["number"]),pc=f("sqlite3_errmsg","string",["number"]),qc=f("sqlite3_column_count","number",["number"]),rc=f("sqlite3_data_count","number",["number"]),sc=f("sqlite3_column_double","number",["number","number"]),vb=f("sqlite3_column_text","string",["number","number"]),tc=f("sqlite3_column_blob","number",["number","number"]),uc=f("sqlite3_column_bytes","number",["number","number"]),vc=f("sqlite3_column_type","number",["number","number"]),wc=
f("sqlite3_column_name","string",["number","number"]),xc=f("sqlite3_reset","number",["number"]),yc=f("sqlite3_clear_bindings","number",["number"]),zc=f("sqlite3_finalize","number",["number"]),Ac=f("sqlite3_create_function_v2","number","number string number number number number number number number".split(" ")),Bc=f("sqlite3_value_type","number",["number"]),Cc=f("sqlite3_value_bytes","number",["number"]),Dc=f("sqlite3_value_text","string",["number"]),Ec=f("sqlite3_value_blob","number",["number"]),
Fc=f("sqlite3_value_double","number",["number"]),Gc=f("sqlite3_result_double","",["number","number"]),wb=f("sqlite3_result_null","",["number"]),Hc=f("sqlite3_result_text","",["number","string","number","number"]),Ic=f("sqlite3_result_blob","",["number","number","number","number"]),Jc=f("sqlite3_result_int","",["number","number"]),xb=f("sqlite3_result_error","",["number","string","number"]),jc=f("RegisterExtensionFunctions","number",["number"]);a.prototype.bind=function(g){if(!this.Ra)throw"Statement closed";
this.reset();return Array.isArray(g)?this.Db(g):null!=g&&"object"===typeof g?this.Eb(g):!0};a.prototype.step=function(){if(!this.Ra)throw"Statement closed";this.Pa=1;var g=oc(this.Ra);switch(g){case 100:return!0;case 101:return!1;default:throw this.db.handleError(g);}};a.prototype.zb=function(g){null==g&&(g=this.Pa,this.Pa+=1);return sc(this.Ra,g)};a.prototype.Ib=function(g){null==g&&(g=this.Pa,this.Pa+=1);g=vb(this.Ra,g);if("function"!==typeof BigInt)throw Error("BigInt is not supported");return BigInt(g)};
a.prototype.Jb=function(g){null==g&&(g=this.Pa,this.Pa+=1);return vb(this.Ra,g)};a.prototype.getBlob=function(g){null==g&&(g=this.Pa,this.Pa+=1);var l=uc(this.Ra,g);g=tc(this.Ra,g);for(var p=new Uint8Array(l),q=0;q<l;q+=1)p[q]=A[g+q];return p};a.prototype.get=function(g,l){l=l||{};null!=g&&this.bind(g)&&this.step();g=[];for(var p=rc(this.Ra),q=0;q<p;q+=1)switch(vc(this.Ra,q)){case 1:var w=l.useBigInt?this.Ib(q):this.zb(q);g.push(w);break;case 2:g.push(this.zb(q));break;case 3:g.push(this.Jb(q));break;
case 4:g.push(this.getBlob(q));break;default:g.push(null)}return g};a.prototype.getColumnNames=function(){for(var g=[],l=qc(this.Ra),p=0;p<l;p+=1)g.push(wc(this.Ra,p));return g};a.prototype.getAsObject=function(g,l){g=this.get(g,l);l=this.getColumnNames();for(var p={},q=0;q<l.length;q+=1)p[l[q]]=g[q];return p};a.prototype.getSQL=function(){return C(this.Ra)};a.prototype.getNormalizedSQL=function(){return J(this.Ra)};a.prototype.run=function(g){null!=g&&this.bind(g);this.step();return this.reset()};
a.prototype.ub=function(g,l){null==l&&(l=this.Pa,this.Pa+=1);g=na(g);var p=oa(g);this.lb.push(p);this.db.handleError(kc(this.Ra,l,p,g.length-1,0))};a.prototype.Cb=function(g,l){null==l&&(l=this.Pa,this.Pa+=1);var p=oa(g);this.lb.push(p);this.db.handleError(ub(this.Ra,l,p,g.length,0))};a.prototype.tb=function(g,l){null==l&&(l=this.Pa,this.Pa+=1);this.db.handleError((g===(g|0)?mc:lc)(this.Ra,l,g))};a.prototype.Fb=function(g){null==g&&(g=this.Pa,this.Pa+=1);ub(this.Ra,g,0,0,0)};a.prototype.vb=function(g,
l){null==l&&(l=this.Pa,this.Pa+=1);switch(typeof g){case "string":this.ub(g,l);return;case "number":this.tb(g,l);return;case "bigint":this.ub(g.toString(),l);return;case "boolean":this.tb(g+0,l);return;case "object":if(null===g){this.Fb(l);return}if(null!=g.length){this.Cb(g,l);return}}throw"Wrong API use : tried to bind a value of an unknown type ("+g+").";};a.prototype.Eb=function(g){var l=this;Object.keys(g).forEach(function(p){var q=nc(l.Ra,p);0!==q&&l.vb(g[p],q)});return!0};a.prototype.Db=function(g){for(var l=
0;l<g.length;l+=1)this.vb(g[l],l+1);return!0};a.prototype.reset=function(){this.freemem();return 0===yc(this.Ra)&&0===xc(this.Ra)};a.prototype.freemem=function(){for(var g;void 0!==(g=this.lb.pop());)pa(g)};a.prototype.free=function(){this.freemem();var g=0===zc(this.Ra);delete this.db.fb[this.Ra];this.Ra=0;return g};b.prototype.next=function(){if(null===this.eb)return{done:!0};null!==this.$a&&(this.$a.free(),this.$a=null);if(!this.db.db)throw this.nb(),Error("Database closed");var g=qa(),l=z(4);
ra(d);ra(l);try{this.db.handleError(ca(this.db.db,this.jb,-1,d,l));this.jb=y(l,"i32");var p=y(d,"i32");if(0===p)return this.nb(),{done:!0};this.$a=new a(p,this.db);this.db.fb[p]=this.$a;return{value:this.$a,done:!1}}catch(q){throw this.pb=B(this.jb),this.nb(),q;}finally{sa(g)}};b.prototype.nb=function(){pa(this.eb);this.eb=null};b.prototype.getRemainingSQL=function(){return null!==this.pb?this.pb:B(this.jb)};"function"===typeof Symbol&&"symbol"===typeof Symbol.iterator&&(b.prototype[Symbol.iterator]=
function(){return this});c.prototype.run=function(g,l){if(!this.db)throw"Database closed";if(l){g=this.prepare(g,l);try{g.step()}finally{g.free()}}else this.handleError(t(this.db,g,0,0,d));return this};c.prototype.exec=function(g,l,p){if(!this.db)throw"Database closed";var q=qa(),w=null;try{var O=ea(g)+1,G=z(O);k(g,A,G,O);var ka=G;var da=z(4);for(g=[];0!==y(ka,"i8");){ra(d);ra(da);this.handleError(ca(this.db,ka,-1,d,da));var D=y(d,"i32");ka=y(da,"i32");if(0!==D){O=null;w=new a(D,this);for(null!=l&&
w.bind(l);w.step();)null===O&&(O={columns:w.getColumnNames(),values:[]},g.push(O)),O.values.push(w.get(null,p));w.free()}}return g}catch(P){throw w&&w.free(),P;}finally{sa(q)}};c.prototype.each=function(g,l,p,q,w){"function"===typeof l&&(q=p,p=l,l=void 0);g=this.prepare(g,l);try{for(;g.step();)p(g.getAsObject(null,w))}finally{g.free()}if("function"===typeof q)return q()};c.prototype.prepare=function(g,l){ra(d);this.handleError(u(this.db,g,-1,d,0));g=y(d,"i32");if(0===g)throw"Nothing to prepare";var p=
new a(g,this);null!=l&&p.bind(l);return this.fb[g]=p};c.prototype.iterateStatements=function(g){return new b(g,this)};c.prototype["export"]=function(){Object.values(this.fb).forEach(function(l){l.free()});Object.values(this.Ya).forEach(ta);this.Ya={};this.handleError(m(this.db));var g=ua(this.filename);this.handleError(h(this.filename,d));this.db=y(d,"i32");return g};c.prototype.close=function(){null!==this.db&&(Object.values(this.fb).forEach(function(g){g.free()}),Object.values(this.Ya).forEach(ta),
this.Ya={},this.handleError(m(this.db)),va("/"+this.filename),this.db=null)};c.prototype.readfile=function(g,l){l=l||{};l.flags=l.flags||"r";l.encoding=l.encoding||"binary";if("utf8"!==l.encoding&&"binary"!==l.encoding)throw Error('Invalid encoding type "'+l.encoding+'"');var p,q=v(g,l.flags);g=wa(g).size;var w=new Uint8Array(g);xa(q,w,0,g,0);"utf8"===l.encoding?p=ya(w,0):"binary"===l.encoding&&(p=w);ma(q);return p};c.prototype.readdir=function(g){g=E(g,{Xa:!0}).node;if(!g.Ma.readdir)throw new F(54);
g=g.Ma.readdir(g);return JSON.stringify(g)};c.prototype.deletefile=function(g){va(g)};c.prototype.writefile=function(g,l,p){p=p||{};p.flags=p.flags||"w";g=v(g,p.flags,p.mode);if("string"===typeof l){var q=new Uint8Array(ea(l)+1);l=k(l,q,0,q.length);la(g,q,0,l,void 0,p.Hb)}else if("object"===typeof l)q=new Uint8Array(l),la(g,q,0,l.byteLength,void 0,p.Hb);else throw Error("Unsupported data type: "+typeof l);ma(g)};c.prototype.handleError=function(g){if(0===g)return null;g=pc(this.db);throw Error(g);
};c.prototype.getRowsModified=function(){return x(this.db)};c.prototype.create_function=function(g,l){Object.prototype.hasOwnProperty.call(this.Ya,g)&&(ta(this.Ya[g]),delete this.Ya[g]);var p=za(function(q,w,O){for(var G,ka=[],da=0;da<w;da+=1){var D=y(O+4*da,"i32"),P=Bc(D);if(1===P||2===P)D=Fc(D);else if(3===P)D=Dc(D);else if(4===P){P=D;D=Cc(P);P=Ec(P);for(var zb=new Uint8Array(D),Fa=0;Fa<D;Fa+=1)zb[Fa]=A[P+Fa];D=zb}else D=null;ka.push(D)}try{G=l.apply(null,ka)}catch(Mc){xb(q,Mc,-1);return}switch(typeof G){case "boolean":Jc(q,
G?1:0);break;case "number":Gc(q,G);break;case "string":Hc(q,G,-1,-1);break;case "object":null===G?wb(q):null!=G.length?(w=oa(G),Ic(q,w,G.length,-1),pa(w)):xb(q,"Wrong API use : tried to return a value of an unknown type ("+G+").",-1);break;default:wb(q)}});this.Ya[g]=p;this.handleError(Ac(this.db,g,l.length,1,0,p,0,0,0));return this};e.Database=c};var Aa={},H;for(H in e)e.hasOwnProperty(H)&&(Aa[H]=e[H]);
var Ba="./this.program",Ca="object"===typeof window,Da="function"===typeof importScripts,Ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,I="",Ga,Ha,Ia,Ja,Ka;
if(Ea)I=Da?require("path").dirname(I)+"/":__dirname+"/",Ga=function(a,b){Ja||(Ja=require("fs"));Ka||(Ka=require("path"));a=Ka.normalize(a);return Ja.readFileSync(a,b?null:"utf8")},Ia=function(a){a=Ga(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||K("Assertion failed: undefined");return a},Ha=function(a,b,c){Ja||(Ja=require("fs"));Ka||(Ka=require("path"));a=Ka.normalize(a);Ja.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(Ba=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),
e.inspect=function(){return"[Emscripten Module object]"};else if(Ca||Da)Da?I=self.location.href:"undefined"!==typeof document&&document.currentScript&&(I=document.currentScript.src),_scriptDir&&(I=_scriptDir),0!==I.indexOf("blob:")?I=I.substr(0,I.lastIndexOf("/")+1):I="",Ga=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},Da&&(Ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
Ha=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var La=e.print||console.log.bind(console),L=e.printErr||console.warn.bind(console);for(H in Aa)Aa.hasOwnProperty(H)&&(e[H]=Aa[H]);Aa=null;e.thisProgram&&(Ba=e.thisProgram);var Ma=[],Na;function ta(a){Na.delete(M.get(a));Ma.push(a)}
function za(a){if(!Na){Na=new WeakMap;for(var b=0;b<M.length;b++){var c=M.get(b);c&&Na.set(c,b)}}if(Na.has(a))a=Na.get(a);else{if(Ma.length)b=Ma.pop();else{try{M.grow(1)}catch(h){if(!(h instanceof RangeError))throw h;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}b=M.length-1}try{M.set(b,a)}catch(h){if(!(h instanceof TypeError))throw h;if("function"===typeof WebAssembly.Function){var d={i:"i32",j:"i64",f:"f32",d:"f64"},f={parameters:[],results:[]};for(c=1;4>c;++c)f.parameters.push(d["viii"[c]]);
c=new WebAssembly.Function(f,a)}else{d=[1,0,1,96];f={i:127,j:126,f:125,d:124};d.push(3);for(c=0;3>c;++c)d.push(f["iii"[c]]);d.push(0);d[1]=d.length-2;c=new Uint8Array([0,97,115,109,1,0,0,0].concat(d,[2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0]));c=new WebAssembly.Module(c);c=(new WebAssembly.Instance(c,{e:{f:a}})).exports.f}M.set(b,c)}Na.set(a,b);a=b}return a}var Oa;e.wasmBinary&&(Oa=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&K("no native wasm support detected");
function ra(a){var b="i32";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":A[a>>0]=0;break;case "i8":A[a>>0]=0;break;case "i16":Pa[a>>1]=0;break;case "i32":N[a>>2]=0;break;case "i64":Q=[0,(R=0,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[a>>2]=Q[0];N[a+4>>2]=Q[1];break;case "float":Qa[a>>2]=0;break;case "double":Ra[a>>3]=0;break;default:K("invalid type for setValue: "+b)}}
function y(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return A[a>>0];case "i8":return A[a>>0];case "i16":return Pa[a>>1];case "i32":return N[a>>2];case "i64":return N[a>>2];case "float":return Qa[a>>2];case "double":return Ra[a>>3];default:K("invalid type for getValue: "+b)}return null}var Sa,Ta=!1;function Ua(a){var b=e["_"+a];b||K("Assertion failed: Cannot call unknown function "+(a+", make sure it is exported"));return b}
function Va(a,b,c,d){var f={string:function(u){var C=0;if(null!==u&&void 0!==u&&0!==u){var J=(u.length<<2)+1;C=z(J);k(u,n,C,J)}return C},array:function(u){var C=z(u.length);A.set(u,C);return C}};a=Ua(a);var h=[],m=0;if(d)for(var t=0;t<d.length;t++){var x=f[c[t]];x?(0===m&&(m=qa()),h[t]=x(d[t])):h[t]=d[t]}c=a.apply(null,h);return c=function(u){0!==m&&sa(m);return"string"===b?B(u):"boolean"===b?!!u:u}(c)}var Wa=0,Xa=1;
function oa(a){var b=Wa==Xa?z(a.length):fa(a.length);a.subarray||a.slice?n.set(a,b):n.set(new Uint8Array(a),b);return b}var Ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ya(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ya)return Ya.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var m=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|m:(f&7)<<18|h<<12|m<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function B(a,b){return a?ya(n,a,b):""}
function k(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var m=a.charCodeAt(h);if(55296<=m&&57343>=m){var t=a.charCodeAt(++h);m=65536+((m&1023)<<10)|t&1023}if(127>=m){if(c>=d)break;b[c++]=m}else{if(2047>=m){if(c+1>=d)break;b[c++]=192|m>>6}else{if(65535>=m){if(c+2>=d)break;b[c++]=224|m>>12}else{if(c+3>=d)break;b[c++]=240|m>>18;b[c++]=128|m>>12&63}b[c++]=128|m>>6&63}b[c++]=128|m&63}}b[c]=0;return c-f}
function ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Za(a){var b=ea(a)+1,c=fa(b);c&&k(a,A,c,b);return c}var $a,A,n,Pa,N,Qa,Ra;
function ab(){var a=Sa.buffer;$a=a;e.HEAP8=A=new Int8Array(a);e.HEAP16=Pa=new Int16Array(a);e.HEAP32=N=new Int32Array(a);e.HEAPU8=n=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=new Uint32Array(a);e.HEAPF32=Qa=new Float32Array(a);e.HEAPF64=Ra=new Float64Array(a)}var M,bb=[],cb=[],db=[];function eb(){var a=e.preRun.shift();bb.unshift(a)}var fb=0,gb=null,hb=null;e.preloadedImages={};e.preloadedAudios={};
function K(a){if(e.onAbort)e.onAbort(a);L(a);Ta=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function ib(){return S.startsWith("data:application/octet-stream;base64,")}var S;if(e.locateFile){if(S="sql-wasm.wasm",!ib()){var jb=S;S=e.locateFile?e.locateFile(jb,I):I+jb}}else S=(new URL("sql-wasm.wasm",import.meta.url)).toString();
function kb(){var a=S;try{if(a==S&&Oa)return new Uint8Array(Oa);if(Ia)return Ia(a);throw"both async and sync fetching of the wasm failed";}catch(b){K(b)}}
function lb(){if(!Oa&&(Ca||Da)){if("function"===typeof fetch&&!S.startsWith("file://"))return fetch(S,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+S+"'";return a.arrayBuffer()}).catch(function(){return kb()});if(Ha)return new Promise(function(a,b){Ha(S,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return kb()})}var R,Q;
function mb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Tb;"number"===typeof c?void 0===b.mb?M.get(c)():M.get(c)(b.mb):c(void 0===b.mb?null:b.mb)}}}function nb(a){return a.replace(/\b_Z[\w\d_]+/g,function(b){return b===b?b:b+" ["+b+"]"})}
function ob(){function a(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?m[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var f=d.getTimezoneOffset(),h=Math.max(b,f);N[pb()>>2]=60*h;N[qb()>>2]=Number(b!=f);c=a(c);d=a(d);c=Za(c);d=Za(d);f<b?(N[rb()>>2]=c,N[rb()+4>>2]=d):(N[rb()>>2]=d,N[rb()+4>>2]=c)}var sb;
function tb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function r(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=tb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function yb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ab(a){if("/"===a)return"/";a=r(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Bb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(Ea)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){K("randomDevice")}}
function Cb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=tb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Db=[];function Eb(a,b){Db[a]={input:[],output:[],cb:b};Fb(a,Gb)}
var Gb={open:function(a){var b=Db[a.node.rdev];if(!b)throw new F(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.cb.flush(a.tty)},flush:function(a){a.tty.cb.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.cb.Ab)throw new F(60);for(var f=0,h=0;h<d;h++){try{var m=a.tty.cb.Ab(a.tty)}catch(t){throw new F(29);}if(void 0===m&&0===f)throw new F(6);if(null===m||void 0===m)break;f++;b[c+h]=m}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.cb.qb)throw new F(60);
try{for(var f=0;f<d;f++)a.tty.cb.qb(a.tty,b[c+f])}catch(h){throw new F(29);}d&&(a.node.timestamp=Date.now());return f}},Hb={Ab:function(a){if(!a.input.length){var b=null;if(Ea){var c=Buffer.alloc(256),d=0;try{d=Ja.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=na(b,!0)}return a.input.shift()},qb:function(a,b){null===b||10===b?(La(ya(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(La(ya(a.output,0)),a.output=[])}},Ib={qb:function(a,b){null===b||10===b?(L(ya(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(L(ya(a.output,0)),a.output=[])}};
function Jb(a){a=65536*Math.ceil(a/65536);var b=Kb(65536,a);if(!b)return 0;n.fill(0,b,b+a);return b}
var T={Va:null,Wa:function(){return T.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);T.Va||(T.Va={dir:{node:{Ua:T.Ma.Ua,Ta:T.Ma.Ta,lookup:T.Ma.lookup,gb:T.Ma.gb,rename:T.Ma.rename,unlink:T.Ma.unlink,rmdir:T.Ma.rmdir,readdir:T.Ma.readdir,symlink:T.Ma.symlink},stream:{Za:T.Na.Za}},file:{node:{Ua:T.Ma.Ua,Ta:T.Ma.Ta},stream:{Za:T.Na.Za,read:T.Na.read,write:T.Na.write,sb:T.Na.sb,hb:T.Na.hb,ib:T.Na.ib}},link:{node:{Ua:T.Ma.Ua,Ta:T.Ma.Ta,
readlink:T.Ma.readlink},stream:{}},wb:{node:{Ua:T.Ma.Ua,Ta:T.Ma.Ta},stream:Lb}});c=Mb(a,b,c,d);U(c.mode)?(c.Ma=T.Va.dir.node,c.Na=T.Va.dir.stream,c.Oa={}):32768===(c.mode&61440)?(c.Ma=T.Va.file.node,c.Na=T.Va.file.stream,c.Sa=0,c.Oa=null):40960===(c.mode&61440)?(c.Ma=T.Va.link.node,c.Na=T.Va.link.stream):8192===(c.mode&61440)&&(c.Ma=T.Va.wb.node,c.Na=T.Va.wb.stream);c.timestamp=Date.now();a&&(a.Oa[b]=c,a.timestamp=c.timestamp);return c},Ub:function(a){return a.Oa?a.Oa.subarray?a.Oa.subarray(0,a.Sa):
new Uint8Array(a.Oa):new Uint8Array(0)},xb:function(a,b){var c=a.Oa?a.Oa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Oa,a.Oa=new Uint8Array(b),0<a.Sa&&a.Oa.set(c.subarray(0,a.Sa),0))},Qb:function(a,b){if(a.Sa!=b)if(0==b)a.Oa=null,a.Sa=0;else{var c=a.Oa;a.Oa=new Uint8Array(b);c&&a.Oa.set(c.subarray(0,Math.min(b,a.Sa)));a.Sa=b}},Ma:{Ua:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;U(a.mode)?
b.size=4096:32768===(a.mode&61440)?b.size=a.Sa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Gb=4096;b.blocks=Math.ceil(b.size/b.Gb);return b},Ta:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.Qb(a,b.size)},lookup:function(){throw Nb[44];},gb:function(a,b,c,d){return T.createNode(a,b,c,d)},rename:function(a,b,c){if(U(a.mode)){try{var d=
Ob(b,c)}catch(h){}if(d)for(var f in d.Oa)throw new F(55);}delete a.parent.Oa[a.name];a.parent.timestamp=Date.now();a.name=c;b.Oa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Oa[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Ob(a,b),d;for(d in c.Oa)throw new F(55);delete a.Oa[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Oa)a.Oa.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},Na:{read:function(a,b,c,d,f){var h=a.node.Oa;if(f>=a.node.Sa)return 0;a=Math.min(a.node.Sa-f,d);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=h[f+d];return a},write:function(a,b,c,d,f,h){b.buffer===A.buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Oa||a.Oa.subarray)){if(h)return a.Oa=b.subarray(c,c+d),a.Sa=d;if(0===a.Sa&&0===f)return a.Oa=b.slice(c,c+d),a.Sa=
d;if(f+d<=a.Sa)return a.Oa.set(b.subarray(c,c+d),f),d}T.xb(a,f+d);if(a.Oa.subarray&&b.subarray)a.Oa.set(b.subarray(c,c+d),f);else for(h=0;h<d;h++)a.Oa[f+h]=b[c+h];a.Sa=Math.max(a.Sa,f+d);return d},Za:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Sa);if(0>b)throw new F(28);return b},sb:function(a,b,c){T.xb(a.node,b+c);a.node.Sa=Math.max(a.node.Sa,b+c)},hb:function(a,b,c,d,f,h){if(0!==b)throw new F(28);if(32768!==(a.node.mode&61440))throw new F(43);a=a.node.Oa;if(h&
2||a.buffer!==$a){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;c=Jb(c);if(!c)throw new F(48);A.set(a,c)}else d=!1,c=a.byteOffset;return{Pb:c,kb:d}},ib:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new F(43);if(f&2)return 0;T.Na.write(a,b,0,d,c,!1);return 0}}},Pb=null,Qb={},V=[],Rb=1,Sb=null,Tb=!0,W={},F=null,Nb={};
function E(a,b){a=Cb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={yb:!0,rb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.rb)throw new F(32);a=tb(a.split("/").filter(function(m){return!!m}),!1);var f=Pb;c="/";for(d=0;d<a.length;d++){var h=d===a.length-1;if(h&&b.parent)break;f=Ob(f,a[d]);c=r(c+"/"+a[d]);f.ab&&(!h||h&&b.yb)&&(f=f.ab.root);if(!h||b.Xa)for(h=0;40960===(f.mode&61440);)if(f=Ub(c),c=Cb(yb(c),f),f=E(c,{rb:b.rb}).node,40<h++)throw new F(32);}return{path:c,node:f}}
function Vb(a){for(var b;;){if(a===a.parent)return a=a.Wa.Bb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Wb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Sb.length}function Xb(a){var b=Wb(a.parent.id,a.name);if(Sb[b]===a)Sb[b]=a.bb;else for(b=Sb[b];b;){if(b.bb===a){b.bb=a.bb;break}b=b.bb}}
function Ob(a,b){var c;if(c=(c=Yb(a,"x"))?c:a.Ma.lookup?0:2)throw new F(c,a);for(c=Sb[Wb(a.id,b)];c;c=c.bb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ma.lookup(a,b)}function Mb(a,b,c,d){a=new Zb(a,b,c,d);b=Wb(a.parent.id,a.name);a.bb=Sb[b];return Sb[b]=a}function U(a){return 16384===(a&61440)}var $b={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function ac(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Yb(a,b){if(Tb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function bc(a,b){try{return Ob(a,b),20}catch(c){}return Yb(a,"wx")}function cc(a,b,c){try{var d=Ob(a,b)}catch(f){return f.Qa}if(a=Yb(a,"wx"))return a;if(c){if(!U(d.mode))return 54;if(d===d.parent||"/"===Vb(d))return 10}else if(U(d.mode))return 31;return 0}function dc(a){var b=4096;for(a=a||0;a<=b;a++)if(!V[a])return a;throw new F(33);}
function ec(a,b){fc||(fc=function(){},fc.prototype={});var c=new fc,d;for(d in a)c[d]=a[d];a=c;b=dc(b);a.fd=b;return V[b]=a}var Lb={open:function(a){a.Na=Qb[a.node.rdev].Na;a.Na.open&&a.Na.open(a)},Za:function(){throw new F(70);}};function Fb(a,b){Qb[a]={Na:b}}
function gc(a,b){var c="/"===b,d=!b;if(c&&Pb)throw new F(10);if(!c&&!d){var f=E(b,{yb:!1});b=f.path;f=f.node;if(f.ab)throw new F(10);if(!U(f.mode))throw new F(54);}b={type:a,Vb:{},Bb:b,Nb:[]};a=a.Wa(b);a.Wa=b;b.root=a;c?Pb=a:f&&(f.ab=b,f.Wa&&f.Wa.Nb.push(b))}function ia(a,b,c){var d=E(a,{parent:!0}).node;a=Ab(a);if(!a||"."===a||".."===a)throw new F(28);var f=bc(d,a);if(f)throw new F(f);if(!d.Ma.gb)throw new F(63);return d.Ma.gb(d,a,b,c)}
function X(a,b){return ia(a,(void 0!==b?b:511)&1023|16384,0)}function hc(a,b,c){"undefined"===typeof c&&(c=b,b=438);ia(a,b|8192,c)}function ic(a,b){if(!Cb(a))throw new F(44);var c=E(b,{parent:!0}).node;if(!c)throw new F(44);b=Ab(b);var d=bc(c,b);if(d)throw new F(d);if(!c.Ma.symlink)throw new F(63);c.Ma.symlink(c,b,a)}
function va(a){var b=E(a,{parent:!0}).node,c=Ab(a),d=Ob(b,c),f=cc(b,c,!1);if(f)throw new F(f);if(!b.Ma.unlink)throw new F(63);if(d.ab)throw new F(10);try{W.willDeletePath&&W.willDeletePath(a)}catch(h){L("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Ma.unlink(b,c);Xb(d);try{if(W.onDeletePath)W.onDeletePath(a)}catch(h){L("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+h.message)}}
function Ub(a){a=E(a).node;if(!a)throw new F(44);if(!a.Ma.readlink)throw new F(28);return Cb(Vb(a.parent),a.Ma.readlink(a))}function wa(a,b){a=E(a,{Xa:!b}).node;if(!a)throw new F(44);if(!a.Ma.Ua)throw new F(63);return a.Ma.Ua(a)}function Kc(a){return wa(a,!0)}function ja(a,b){a="string"===typeof a?E(a,{Xa:!0}).node:a;if(!a.Ma.Ta)throw new F(63);a.Ma.Ta(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Lc(a){a="string"===typeof a?E(a,{Xa:!0}).node:a;if(!a.Ma.Ta)throw new F(63);a.Ma.Ta(a,{timestamp:Date.now()})}function Nc(a,b){if(0>b)throw new F(28);a="string"===typeof a?E(a,{Xa:!0}).node:a;if(!a.Ma.Ta)throw new F(63);if(U(a.mode))throw new F(31);if(32768!==(a.mode&61440))throw new F(28);var c=Yb(a,"w");if(c)throw new F(c);a.Ma.Ta(a,{size:b,timestamp:Date.now()})}
function v(a,b,c,d){if(""===a)throw new F(44);if("string"===typeof b){var f=$b[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var h=a;else{a=r(a);try{h=E(a,{Xa:!(b&131072)}).node}catch(m){}}f=!1;if(b&64)if(h){if(b&128)throw new F(20);}else h=ia(a,c,0),f=!0;if(!h)throw new F(44);8192===(h.mode&61440)&&(b&=-513);if(b&65536&&!U(h.mode))throw new F(54);if(!f&&(c=h?40960===(h.mode&61440)?32:U(h.mode)&&
("r"!==ac(b)||b&512)?31:Yb(h,ac(b)):44))throw new F(c);b&512&&Nc(h,0);b&=-131713;d=ec({node:h,path:Vb(h),flags:b,seekable:!0,position:0,Na:h.Na,Sb:[],error:!1},d);d.Na.open&&d.Na.open(d);!e.logReadFiles||b&1||(Oc||(Oc={}),a in Oc||(Oc[a]=1,L("FS.trackingDelegate error on read file: "+a)));try{W.onOpenFile&&(h=0,1!==(b&2097155)&&(h|=1),0!==(b&2097155)&&(h|=2),W.onOpenFile(a,h))}catch(m){L("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+m.message)}return d}
function ma(a){if(null===a.fd)throw new F(8);a.ob&&(a.ob=null);try{a.Na.close&&a.Na.close(a)}catch(b){throw b;}finally{V[a.fd]=null}a.fd=null}function Pc(a,b,c){if(null===a.fd)throw new F(8);if(!a.seekable||!a.Na.Za)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.Na.Za(a,b,c);a.Sb=[]}
function xa(a,b,c,d,f){if(0>d||0>f)throw new F(28);if(null===a.fd)throw new F(8);if(1===(a.flags&2097155))throw new F(8);if(U(a.node.mode))throw new F(31);if(!a.Na.read)throw new F(28);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new F(70);b=a.Na.read(a,b,c,d,f);h||(a.position+=b);return b}
function la(a,b,c,d,f,h){if(0>d||0>f)throw new F(28);if(null===a.fd)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(U(a.node.mode))throw new F(31);if(!a.Na.write)throw new F(28);a.seekable&&a.flags&1024&&Pc(a,0,2);var m="undefined"!==typeof f;if(!m)f=a.position;else if(!a.seekable)throw new F(70);b=a.Na.write(a,b,c,d,f,h);m||(a.position+=b);try{if(a.path&&W.onWriteToFile)W.onWriteToFile(a.path)}catch(t){L("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+t.message)}return b}
function ua(a){var b={encoding:"binary"};b=b||{};b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error('Invalid encoding type "'+b.encoding+'"');var c,d=v(a,b.flags);a=wa(a).size;var f=new Uint8Array(a);xa(d,f,0,a,0);"utf8"===b.encoding?c=ya(f,0):"binary"===b.encoding&&(c=f);ma(d);return c}
function Qc(){F||(F=function(a,b){this.node=b;this.Rb=function(c){this.Qa=c};this.Rb(a);this.message="FS error"},F.prototype=Error(),F.prototype.constructor=F,[44].forEach(function(a){Nb[a]=new F(a);Nb[a].stack="<generic error, no stack>"}))}var Rc;function ha(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Sc(a,b,c){a=r("/dev/"+a);var d=ha(!!b,!!c);Tc||(Tc=64);var f=Tc++<<8|0;Fb(f,{open:function(h){h.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(h,m,t,x){for(var u=0,C=0;C<x;C++){try{var J=b()}catch(ca){throw new F(29);}if(void 0===J&&0===u)throw new F(6);if(null===J||void 0===J)break;u++;m[t+C]=J}u&&(h.node.timestamp=Date.now());return u},write:function(h,m,t,x){for(var u=0;u<x;u++)try{c(m[t+u])}catch(C){throw new F(29);}x&&(h.node.timestamp=Date.now());return u}});
hc(a,d,f)}var Tc,Y={},fc,Oc,Uc={};
function Vc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&r(b)!==r(Vb(f.node)))return-54;throw f;}N[c>>2]=d.dev;N[c+4>>2]=0;N[c+8>>2]=d.ino;N[c+12>>2]=d.mode;N[c+16>>2]=d.nlink;N[c+20>>2]=d.uid;N[c+24>>2]=d.gid;N[c+28>>2]=d.rdev;N[c+32>>2]=0;Q=[d.size>>>0,(R=d.size,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[c+40>>2]=Q[0];N[c+44>>2]=Q[1];N[c+48>>2]=4096;N[c+52>>2]=d.blocks;N[c+56>>2]=d.atime.getTime()/1E3|0;N[c+60>>2]=
0;N[c+64>>2]=d.mtime.getTime()/1E3|0;N[c+68>>2]=0;N[c+72>>2]=d.ctime.getTime()/1E3|0;N[c+76>>2]=0;Q=[d.ino>>>0,(R=d.ino,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[c+80>>2]=Q[0];N[c+84>>2]=Q[1];return 0}var Wc=void 0;function Xc(){Wc+=4;return N[Wc-4>>2]}function Z(a){a=V[a];if(!a)throw new F(8);return a}var Yc;Yc=Ea?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};
var Zc={};function $c(){if(!ad){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:Ba||"./this.program"},b;for(b in Zc)void 0===Zc[b]?delete a[b]:a[b]=Zc[b];var c=[];for(b in a)c.push(b+"="+a[b]);ad=c}return ad}var ad;
function Zb(a,b,c,d){a||(a=this);this.parent=a;this.Wa=a.Wa;this.ab=null;this.id=Rb++;this.name=b;this.mode=c;this.Ma={};this.Na={};this.rdev=d}Object.defineProperties(Zb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Qc();Sb=Array(4096);gc(T,"/");X("/tmp");X("/home");X("/home/web_user");
(function(){X("/dev");Fb(259,{read:function(){return 0},write:function(b,c,d,f){return f}});hc("/dev/null",259);Eb(1280,Hb);Eb(1536,Ib);hc("/dev/tty",1280);hc("/dev/tty1",1536);var a=Bb();Sc("random",a);Sc("urandom",a);X("/dev/shm");X("/dev/shm/tmp")})();
(function(){X("/proc");var a=X("/proc/self");X("/proc/self/fd");gc({Wa:function(){var b=Mb(a,"fd",16895,73);b.Ma={lookup:function(c,d){var f=V[+d];if(!f)throw new F(8);c={parent:null,Wa:{Bb:"fake"},Ma:{readlink:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();function na(a,b){var c=Array(ea(a)+1);a=k(a,c,0,c.length);b&&(c.length=a);return c}
var cd={a:function(a,b,c,d){K("Assertion failed: "+B(a)+", at: "+[b?B(b):"unknown filename",c,d?B(d):"unknown function"])},q:function(a,b){sb||(sb=!0,ob());a=new Date(1E3*N[a>>2]);N[b>>2]=a.getSeconds();N[b+4>>2]=a.getMinutes();N[b+8>>2]=a.getHours();N[b+12>>2]=a.getDate();N[b+16>>2]=a.getMonth();N[b+20>>2]=a.getFullYear()-1900;N[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);N[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;N[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;N[b+32>>2]=a;a=N[rb()+(a?4:0)>>2];N[b+40>>2]=a;return b},t:function(a,b){try{a=B(a);if(b&-8)var c=-28;else{var d;(d=E(a,{Xa:!0}).node)?(a="",b&4&&(a+="r"),b&2&&(a+="w"),b&1&&(a+="x"),c=a&&Yb(d,a)?-2:0):c=-44}return c}catch(f){return"undefined"!==typeof Y&&f instanceof F||K(f),-f.Qa}},F:function(a,b){try{return a=B(a),ja(a,b),0}catch(c){return"undefined"!==typeof Y&&c instanceof F||K(c),-c.Qa}},u:function(a){try{return a=
B(a),Lc(a),0}catch(b){return"undefined"!==typeof Y&&b instanceof F||K(b),-b.Qa}},G:function(a,b){try{var c=V[a];if(!c)throw new F(8);ja(c.node,b);return 0}catch(d){return"undefined"!==typeof Y&&d instanceof F||K(d),-d.Qa}},v:function(a){try{var b=V[a];if(!b)throw new F(8);Lc(b.node);return 0}catch(c){return"undefined"!==typeof Y&&c instanceof F||K(c),-c.Qa}},b:function(a,b,c){Wc=c;try{var d=Z(a);switch(b){case 0:var f=Xc();return 0>f?-28:v(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;
case 4:return f=Xc(),d.flags|=f,0;case 12:return f=Xc(),Pa[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return N[bd()>>2]=28,-1;default:return-28}}catch(h){return"undefined"!==typeof Y&&h instanceof F||K(h),-h.Qa}},H:function(a,b){try{var c=Z(a);return Vc(wa,c.path,b)}catch(d){return"undefined"!==typeof Y&&d instanceof F||K(d),-d.Qa}},D:function(a,b,c){try{var d=V[a];if(!d)throw new F(8);if(0===(d.flags&2097155))throw new F(28);Nc(d.node,c);return 0}catch(f){return"undefined"!==
typeof Y&&f instanceof F||K(f),-f.Qa}},y:function(a,b){try{if(0===b)return-28;if(b<ea("/")+1)return-68;k("/",n,a,b);return a}catch(c){return"undefined"!==typeof Y&&c instanceof F||K(c),-c.Qa}},z:function(){return 0},e:function(){return 42},j:function(a,b,c){Wc=c;try{var d=Z(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Xc();return N[f>>2]=0;case 21520:return d.tty?-28:
-59;case 21531:a=f=Xc();if(!d.Na.Kb)throw new F(59);return d.Na.Kb(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:K("bad ioctl syscall "+b)}}catch(h){return"undefined"!==typeof Y&&h instanceof F||K(h),-h.Qa}},J:function(a,b){try{return a=B(a),Vc(Kc,a,b)}catch(c){return"undefined"!==typeof Y&&c instanceof F||K(c),-c.Qa}},I:function(a,b){try{return a=B(a),a=r(a),"/"===a[a.length-1]&&(a=a.substr(0,a.length-1)),X(a,b),0}catch(c){return"undefined"!==typeof Y&&c instanceof F||
K(c),-c.Qa}},r:function(a,b,c,d,f,h){try{a:{h<<=12;var m=!1;if(0!==(d&16)&&0!==a%65536)var t=-28;else{if(0!==(d&32)){var x=Jb(b);if(!x){t=-48;break a}m=!0}else{var u=V[f];if(!u){t=-8;break a}var C=h;if(0!==(c&2)&&0===(d&2)&&2!==(u.flags&2097155))throw new F(2);if(1===(u.flags&2097155))throw new F(2);if(!u.Na.hb)throw new F(43);var J=u.Na.hb(u,a,b,C,c,d);x=J.Pb;m=J.kb}Uc[x]={Mb:x,Lb:b,kb:m,fd:f,Ob:c,flags:d,offset:h};t=x}}return t}catch(ca){return"undefined"!==typeof Y&&ca instanceof F||K(ca),-ca.Qa}},
s:function(a,b){try{var c=Uc[a];if(0!==b&&c){if(b===c.Lb){var d=V[c.fd];if(d&&c.Ob&2){var f=c.flags,h=c.offset,m=n.slice(a,a+b);d&&d.Na.ib&&d.Na.ib(d,m,h,b,f)}Uc[a]=null;c.kb&&pa(c.Mb)}var t=0}else t=-28;return t}catch(x){return"undefined"!==typeof Y&&x instanceof F||K(x),-x.Qa}},h:function(a,b,c){Wc=c;try{var d=B(a),f=c?Xc():0;return v(d,b,f).fd}catch(h){return"undefined"!==typeof Y&&h instanceof F||K(h),-h.Qa}},w:function(a,b,c){try{a=B(a);if(0>=c)var d=-28;else{var f=Ub(a),h=Math.min(c,ea(f)),
m=A[b+h];k(f,n,b,c+1);A[b+h]=m;d=h}return d}catch(t){return"undefined"!==typeof Y&&t instanceof F||K(t),-t.Qa}},x:function(a){try{a=B(a);var b=E(a,{parent:!0}).node,c=Ab(a),d=Ob(b,c),f=cc(b,c,!0);if(f)throw new F(f);if(!b.Ma.rmdir)throw new F(63);if(d.ab)throw new F(10);try{W.willDeletePath&&W.willDeletePath(a)}catch(h){L("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Ma.rmdir(b,c);Xb(d);try{if(W.onDeletePath)W.onDeletePath(a)}catch(h){L("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}return 0}catch(h){return"undefined"!==typeof Y&&h instanceof F||K(h),-h.Qa}},i:function(a,b){try{return a=B(a),Vc(wa,a,b)}catch(c){return"undefined"!==typeof Y&&c instanceof F||K(c),-c.Qa}},A:function(a){try{return a=B(a),va(a),0}catch(b){return"undefined"!==typeof Y&&b instanceof F||K(b),-b.Qa}},E:function(){return 2147483648},l:function(a,b,c){n.copyWithin(a,b,b+c)},d:function(a){var b=n.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*
(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{Sa.grow(Math.min(2147483648,d)-$a.byteLength+65535>>>16);ab();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},p:function(a){for(var b=Yc();Yc()-b<a;);},n:function(a,b){var c=0;$c().forEach(function(d,f){var h=b+c;f=N[a+4*f>>2]=h;for(h=0;h<d.length;++h)A[f++>>0]=d.charCodeAt(h);A[f>>0]=0;c+=d.length+1});return 0},o:function(a,b){var c=$c();N[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});
N[b>>2]=d;return 0},c:function(a){try{var b=Z(a);ma(b);return 0}catch(c){return"undefined"!==typeof Y&&c instanceof F||K(c),c.Qa}},m:function(a,b){try{var c=Z(a);A[b>>0]=c.tty?2:U(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof Y&&d instanceof F||K(d),d.Qa}},g:function(a,b,c,d){try{a:{for(var f=Z(a),h=a=0;h<c;h++){var m=N[b+(8*h+4)>>2],t=xa(f,A,N[b+8*h>>2],m,void 0);if(0>t){var x=-1;break a}a+=t;if(t<m)break}x=a}N[d>>2]=x;return 0}catch(u){return"undefined"!==typeof Y&&
u instanceof F||K(u),u.Qa}},k:function(a,b,c,d,f){try{var h=Z(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Pc(h,a,d);Q=[h.position>>>0,(R=h.position,1<=+Math.abs(R)?0<R?(Math.min(+Math.floor(R/4294967296),4294967295)|0)>>>0:~~+Math.ceil((R-+(~~R>>>0))/4294967296)>>>0:0)];N[f>>2]=Q[0];N[f+4>>2]=Q[1];h.ob&&0===a&&0===d&&(h.ob=null);return 0}catch(m){return"undefined"!==typeof Y&&m instanceof F||K(m),m.Qa}},C:function(a){try{var b=Z(a);return b.Na&&b.Na.fsync?-b.Na.fsync(b):
0}catch(c){return"undefined"!==typeof Y&&c instanceof F||K(c),c.Qa}},f:function(a,b,c,d){try{a:{for(var f=Z(a),h=a=0;h<c;h++){var m=la(f,A,N[b+8*h>>2],N[b+(8*h+4)>>2],void 0);if(0>m){var t=-1;break a}a+=m}t=a}N[d>>2]=t;return 0}catch(x){return"undefined"!==typeof Y&&x instanceof F||K(x),x.Qa}},K:function(a){var b=Date.now();N[a>>2]=b/1E3|0;N[a+4>>2]=b%1E3*1E3|0;return 0},L:function(a){var b=Date.now()/1E3|0;a&&(N[a>>2]=b);return b},B:function(a,b){if(b){var c=b+8;b=1E3*N[c>>2];b+=N[c+4>>2]/1E3}else b=
Date.now();a=B(a);try{var d=E(a,{Xa:!0}).node;d.Ma.Ta(d,{timestamp:Math.max(b,b)});var f=0}catch(h){if(!(h instanceof F)){b:{f=Error();if(!f.stack){try{throw Error();}catch(m){f=m}if(!f.stack){f="(no stack trace available)";break b}}f=f.stack.toString()}e.extraStackTrace&&(f+="\n"+e.extraStackTrace());f=nb(f);throw h+" : "+f;}f=h.Qa;N[bd()>>2]=f;f=-1}return f}};
(function(){function a(f){e.asm=f.exports;Sa=e.asm.M;ab();M=e.asm.Da;cb.unshift(e.asm.N);fb--;e.monitorRunDependencies&&e.monitorRunDependencies(fb);0==fb&&(null!==gb&&(clearInterval(gb),gb=null),hb&&(f=hb,hb=null,f()))}function b(f){a(f.instance)}function c(f){return lb().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(f,function(h){L("failed to asynchronously prepare wasm: "+h);K(h)})}var d={a:cd};fb++;e.monitorRunDependencies&&e.monitorRunDependencies(fb);
if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return L("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Oa||"function"!==typeof WebAssembly.instantiateStreaming||ib()||S.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(S,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){L("wasm streaming compile failed: "+h);L("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);
return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.N).apply(null,arguments)};e._sqlite3_free=function(){return(e._sqlite3_free=e.asm.O).apply(null,arguments)};e._sqlite3_value_double=function(){return(e._sqlite3_value_double=e.asm.P).apply(null,arguments)};e._sqlite3_value_text=function(){return(e._sqlite3_value_text=e.asm.Q).apply(null,arguments)};var bd=e.___errno_location=function(){return(bd=e.___errno_location=e.asm.R).apply(null,arguments)};
e._sqlite3_prepare_v2=function(){return(e._sqlite3_prepare_v2=e.asm.S).apply(null,arguments)};e._sqlite3_step=function(){return(e._sqlite3_step=e.asm.T).apply(null,arguments)};e._sqlite3_finalize=function(){return(e._sqlite3_finalize=e.asm.U).apply(null,arguments)};e._sqlite3_reset=function(){return(e._sqlite3_reset=e.asm.V).apply(null,arguments)};e._sqlite3_value_int=function(){return(e._sqlite3_value_int=e.asm.W).apply(null,arguments)};
e._sqlite3_clear_bindings=function(){return(e._sqlite3_clear_bindings=e.asm.X).apply(null,arguments)};e._sqlite3_value_blob=function(){return(e._sqlite3_value_blob=e.asm.Y).apply(null,arguments)};e._sqlite3_value_bytes=function(){return(e._sqlite3_value_bytes=e.asm.Z).apply(null,arguments)};e._sqlite3_value_type=function(){return(e._sqlite3_value_type=e.asm._).apply(null,arguments)};e._sqlite3_result_blob=function(){return(e._sqlite3_result_blob=e.asm.$).apply(null,arguments)};
e._sqlite3_result_double=function(){return(e._sqlite3_result_double=e.asm.aa).apply(null,arguments)};e._sqlite3_result_error=function(){return(e._sqlite3_result_error=e.asm.ba).apply(null,arguments)};e._sqlite3_result_int=function(){return(e._sqlite3_result_int=e.asm.ca).apply(null,arguments)};e._sqlite3_result_int64=function(){return(e._sqlite3_result_int64=e.asm.da).apply(null,arguments)};e._sqlite3_result_null=function(){return(e._sqlite3_result_null=e.asm.ea).apply(null,arguments)};
e._sqlite3_result_text=function(){return(e._sqlite3_result_text=e.asm.fa).apply(null,arguments)};e._sqlite3_sql=function(){return(e._sqlite3_sql=e.asm.ga).apply(null,arguments)};e._sqlite3_column_count=function(){return(e._sqlite3_column_count=e.asm.ha).apply(null,arguments)};e._sqlite3_data_count=function(){return(e._sqlite3_data_count=e.asm.ia).apply(null,arguments)};e._sqlite3_column_blob=function(){return(e._sqlite3_column_blob=e.asm.ja).apply(null,arguments)};
e._sqlite3_column_bytes=function(){return(e._sqlite3_column_bytes=e.asm.ka).apply(null,arguments)};e._sqlite3_column_double=function(){return(e._sqlite3_column_double=e.asm.la).apply(null,arguments)};e._sqlite3_column_text=function(){return(e._sqlite3_column_text=e.asm.ma).apply(null,arguments)};e._sqlite3_column_type=function(){return(e._sqlite3_column_type=e.asm.na).apply(null,arguments)};e._sqlite3_column_name=function(){return(e._sqlite3_column_name=e.asm.oa).apply(null,arguments)};
e._sqlite3_bind_blob=function(){return(e._sqlite3_bind_blob=e.asm.pa).apply(null,arguments)};e._sqlite3_bind_double=function(){return(e._sqlite3_bind_double=e.asm.qa).apply(null,arguments)};e._sqlite3_bind_int=function(){return(e._sqlite3_bind_int=e.asm.ra).apply(null,arguments)};e._sqlite3_bind_text=function(){return(e._sqlite3_bind_text=e.asm.sa).apply(null,arguments)};e._sqlite3_bind_parameter_index=function(){return(e._sqlite3_bind_parameter_index=e.asm.ta).apply(null,arguments)};
e._sqlite3_normalized_sql=function(){return(e._sqlite3_normalized_sql=e.asm.ua).apply(null,arguments)};e._sqlite3_errmsg=function(){return(e._sqlite3_errmsg=e.asm.va).apply(null,arguments)};e._sqlite3_exec=function(){return(e._sqlite3_exec=e.asm.wa).apply(null,arguments)};e._sqlite3_changes=function(){return(e._sqlite3_changes=e.asm.xa).apply(null,arguments)};e._sqlite3_close_v2=function(){return(e._sqlite3_close_v2=e.asm.ya).apply(null,arguments)};
e._sqlite3_create_function_v2=function(){return(e._sqlite3_create_function_v2=e.asm.za).apply(null,arguments)};e._sqlite3_open=function(){return(e._sqlite3_open=e.asm.Aa).apply(null,arguments)};var fa=e._malloc=function(){return(fa=e._malloc=e.asm.Ba).apply(null,arguments)},pa=e._free=function(){return(pa=e._free=e.asm.Ca).apply(null,arguments)};e._RegisterExtensionFunctions=function(){return(e._RegisterExtensionFunctions=e.asm.Ea).apply(null,arguments)};
var rb=e.__get_tzname=function(){return(rb=e.__get_tzname=e.asm.Fa).apply(null,arguments)},qb=e.__get_daylight=function(){return(qb=e.__get_daylight=e.asm.Ga).apply(null,arguments)},pb=e.__get_timezone=function(){return(pb=e.__get_timezone=e.asm.Ha).apply(null,arguments)},qa=e.stackSave=function(){return(qa=e.stackSave=e.asm.Ia).apply(null,arguments)},sa=e.stackRestore=function(){return(sa=e.stackRestore=e.asm.Ja).apply(null,arguments)},z=e.stackAlloc=function(){return(z=e.stackAlloc=e.asm.Ka).apply(null,
arguments)},Kb=e._memalign=function(){return(Kb=e._memalign=e.asm.La).apply(null,arguments)};e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(function(h){return"number"===h});return"string"!==b&&f&&!d?Ua(a):function(){return Va(a,b,c,arguments)}};e.UTF8ToString=B;e.stackSave=qa;e.stackRestore=sa;e.stackAlloc=z;var dd;hb=function ed(){dd||fd();dd||(hb=ed)};
function fd(){function a(){if(!dd&&(dd=!0,e.calledRun=!0,!Ta)){e.noFSInit||Rc||(Rc=!0,Qc(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?Sc("stdin",e.stdin):ic("/dev/tty","/dev/stdin"),e.stdout?Sc("stdout",null,e.stdout):ic("/dev/tty","/dev/stdout"),e.stderr?Sc("stderr",null,e.stderr):ic("/dev/tty1","/dev/stderr"),v("/dev/stdin",0),v("/dev/stdout",1),v("/dev/stderr",1));Tb=!1;mb(cb);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&
(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();db.unshift(b)}mb(db)}}if(!(0<fb)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)eb();mb(bb);0<fb||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=fd;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();fd();


  return Module.ready
}
);
})();
export default Module;