
// We are modularizing this manually because the current modularize setting in Emscripten has some issues:
// https://github.com/kripken/emscripten/issues/5820
// In addition, When you use emcc's modularization, it still expects to export a global object called `Module`,
// which is able to be used/called before the WASM is loaded.
// The modularization below exports a promise that loads and resolves to the actual sql.js module.
// That way, this module can't be used before the WASM is finished loading.

// We are going to define a function that a user will call to start loading initializing our Sql.js library
// However, that function might be called multiple times, and on subsequent calls, we don't actually want it to instantiate a new instance of the Module
// Instead, we want to return the previously loaded module

// TODO: Make this not declare a global if used in the browser
var initSqlJsPromise = undefined;

var initSqlJs = function (moduleConfig) {

    if (initSqlJsPromise){
      return initSqlJsPromise;
    }
    // If we're here, we've never called this function before
    initSqlJsPromise = new Promise(function (resolveModule, reject) {

        // We are modularizing this manually because the current modularize setting in Emscripten has some issues:
        // https://github.com/kripken/emscripten/issues/5820

        // The way to affect the loading of emcc compiled modules is to create a variable called `Module` and add
        // properties to it, like `preRun`, `postRun`, etc
        // We are using that to get notified when the WASM has finished loading.
        // Only then will we return our promise

        // If they passed in a moduleConfig object, use that
        // Otherwise, initialize Module to the empty object
        var Module = typeof moduleConfig !== 'undefined' ? moduleConfig : {};

        // EMCC only allows for a single onAbort function (not an array of functions)
        // So if the user defined their own onAbort function, we remember it and call it
        var originalOnAbortFunction = Module['onAbort'];
        Module['onAbort'] = function (errorThatCausedAbort) {
            reject(new Error(errorThatCausedAbort));
            if (originalOnAbortFunction){
              originalOnAbortFunction(errorThatCausedAbort);
            }
        };

        Module['postRun'] = Module['postRun'] || [];
        Module['postRun'].push(function () {
            // When Emscripted calls postRun, this promise resolves with the built Module
            resolveModule(Module);
        });

        // There is a section of code in the emcc-generated code below that looks like this:
        // (Note that this is lowercase `module`)
        // if (typeof module !== 'undefined') {
        //     module['exports'] = Module;
        // }
        // When that runs, it's going to overwrite our own modularization export efforts in shell-post.js!
        // The only way to tell emcc not to emit it is to pass the MODULARIZE=1 or MODULARIZE_INSTANCE=1 flags,
        // but that carries with it additional unnecessary baggage/bugs we don't want either.
        // So, we have three options:
        // 1) We undefine `module`
        // 2) We remember what `module['exports']` was at the beginning of this function and we restore it later
        // 3) We write a script to remove those lines of code as part of the Make process.
        //
        // Since those are the only lines of code that care about module, we will undefine it. It's the most straightforward
        // of the options, and has the side effect of reducing emcc's efforts to modify the module if its output were to change in the future.
        // That's a nice side effect since we're handling the modularization efforts ourselves
        module = undefined;

        // The emcc-generated code and shell-post.js code goes below,
        // meaning that all of it runs inside of this promise. If anything throws an exception, our promise will abort

var e;e||(e=typeof Module !== 'undefined' ? Module : {});null;
e.onRuntimeInitialized=function(){function a(g,m){switch(typeof m){case "boolean":uc(g,m?1:0);break;case "number":vc(g,m);break;case "string":wc(g,m,-1,-1);break;case "object":if(null===m)Bb(g);else if(null!=m.length){var r=aa(m);xc(g,r,m.length,-1);da(r)}else La(g,"Wrong API use : tried to return a value of an unknown type ("+m+").",-1);break;default:Bb(g)}}function b(g,m){for(var r=[],w=0;w<g;w+=1){var y=l(m+4*w,"i32"),A=yc(y);if(1===A||2===A)y=zc(y);else if(3===A)y=Ac(y);else if(4===A){A=y;y=Bc(A);
A=Cc(A);for(var U=new Uint8Array(y),N=0;N<y;N+=1)U[N]=t[A+N];y=U}else y=null;r.push(y)}return r}function c(g,m){this.La=g;this.db=m;this.Ja=1;this.fb=[]}function d(g,m){this.db=m;m=ea(g)+1;this.Za=fa(m);if(null===this.Za)throw Error("Unable to allocate memory for the SQL string");ha(g,u,this.Za,m);this.eb=this.Za;this.Va=this.jb=null}function f(g){this.filename="dbfile_"+(4294967295*Math.random()>>>0);null!=g&&ia("/",this.filename,g,!0,!0);this.handleError(n(this.filename,h));this.db=l(h,"i32");Dc(this.db);
this.ab={};this.Na={}}var h=v(4),k=e.cwrap,n=k("sqlite3_open","number",["string","number"]),x=k("sqlite3_close_v2","number",["number"]),p=k("sqlite3_exec","number",["number","string","number","number","number"]),z=k("sqlite3_changes","number",["number"]),q=k("sqlite3_prepare_v2","number",["number","string","number","number","number"]),B=k("sqlite3_sql","string",["number"]),H=k("sqlite3_normalized_sql","string",["number"]),G=k("sqlite3_prepare_v2","number",["number","number","number","number","number"]),
I=k("sqlite3_bind_text","number",["number","number","number","number","number"]),J=k("sqlite3_bind_blob","number",["number","number","number","number","number"]),ba=k("sqlite3_bind_double","number",["number","number","number"]),ka=k("sqlite3_bind_int","number",["number","number","number"]),ca=k("sqlite3_bind_parameter_index","number",["number","string"]),cb=k("sqlite3_step","number",["number"]),L=k("sqlite3_errmsg","string",["number"]),Ec=k("sqlite3_column_count","number",["number"]),Fc=k("sqlite3_data_count",
"number",["number"]),Gc=k("sqlite3_column_double","number",["number","number"]),Cb=k("sqlite3_column_text","string",["number","number"]),Hc=k("sqlite3_column_blob","number",["number","number"]),Ic=k("sqlite3_column_bytes","number",["number","number"]),Jc=k("sqlite3_column_type","number",["number","number"]),Kc=k("sqlite3_column_name","string",["number","number"]),Lc=k("sqlite3_reset","number",["number"]),Mc=k("sqlite3_clear_bindings","number",["number"]),Nc=k("sqlite3_finalize","number",["number"]),
Db=k("sqlite3_create_function_v2","number","number string number number number number number number number".split(" ")),yc=k("sqlite3_value_type","number",["number"]),Bc=k("sqlite3_value_bytes","number",["number"]),Ac=k("sqlite3_value_text","string",["number"]),Cc=k("sqlite3_value_blob","number",["number"]),zc=k("sqlite3_value_double","number",["number"]),vc=k("sqlite3_result_double","",["number","number"]),Bb=k("sqlite3_result_null","",["number"]),wc=k("sqlite3_result_text","",["number","string",
"number","number"]),xc=k("sqlite3_result_blob","",["number","number","number","number"]),uc=k("sqlite3_result_int","",["number","number"]),La=k("sqlite3_result_error","",["number","string","number"]),Eb=k("sqlite3_aggregate_context","number",["number","number"]),Dc=k("RegisterExtensionFunctions","number",["number"]);c.prototype.bind=function(g){if(!this.La)throw"Statement closed";this.reset();return Array.isArray(g)?this.Fb(g):null!=g&&"object"===typeof g?this.Gb(g):!0};c.prototype.step=function(){if(!this.La)throw"Statement closed";
this.Ja=1;var g=cb(this.La);switch(g){case 100:return!0;case 101:return!1;default:throw this.db.handleError(g);}};c.prototype.vb=function(g){null==g&&(g=this.Ja,this.Ja+=1);return Gc(this.La,g)};c.prototype.Kb=function(g){null==g&&(g=this.Ja,this.Ja+=1);g=Cb(this.La,g);if("function"!==typeof BigInt)throw Error("BigInt is not supported");return BigInt(g)};c.prototype.Lb=function(g){null==g&&(g=this.Ja,this.Ja+=1);return Cb(this.La,g)};c.prototype.getBlob=function(g){null==g&&(g=this.Ja,this.Ja+=1);
var m=Ic(this.La,g);g=Hc(this.La,g);for(var r=new Uint8Array(m),w=0;w<m;w+=1)r[w]=t[g+w];return r};c.prototype.get=function(g,m){m=m||{};null!=g&&this.bind(g)&&this.step();g=[];for(var r=Fc(this.La),w=0;w<r;w+=1)switch(Jc(this.La,w)){case 1:var y=m.useBigInt?this.Kb(w):this.vb(w);g.push(y);break;case 2:g.push(this.vb(w));break;case 3:g.push(this.Lb(w));break;case 4:g.push(this.getBlob(w));break;default:g.push(null)}return g};c.prototype.getColumnNames=function(){for(var g=[],m=Ec(this.La),r=0;r<m;r+=
1)g.push(Kc(this.La,r));return g};c.prototype.getAsObject=function(g,m){g=this.get(g,m);m=this.getColumnNames();for(var r={},w=0;w<m.length;w+=1)r[m[w]]=g[w];return r};c.prototype.getSQL=function(){return B(this.La)};c.prototype.getNormalizedSQL=function(){return H(this.La)};c.prototype.run=function(g){null!=g&&this.bind(g);this.step();return this.reset()};c.prototype.pb=function(g,m){null==m&&(m=this.Ja,this.Ja+=1);g=ja(g);var r=aa(g);this.fb.push(r);this.db.handleError(I(this.La,m,r,g.length-1,
0))};c.prototype.Eb=function(g,m){null==m&&(m=this.Ja,this.Ja+=1);var r=aa(g);this.fb.push(r);this.db.handleError(J(this.La,m,r,g.length,0))};c.prototype.ob=function(g,m){null==m&&(m=this.Ja,this.Ja+=1);this.db.handleError((g===(g|0)?ka:ba)(this.La,m,g))};c.prototype.Hb=function(g){null==g&&(g=this.Ja,this.Ja+=1);J(this.La,g,0,0,0)};c.prototype.qb=function(g,m){null==m&&(m=this.Ja,this.Ja+=1);switch(typeof g){case "string":this.pb(g,m);return;case "number":this.ob(g,m);return;case "bigint":this.pb(g.toString(),
m);return;case "boolean":this.ob(g+0,m);return;case "object":if(null===g){this.Hb(m);return}if(null!=g.length){this.Eb(g,m);return}}throw"Wrong API use : tried to bind a value of an unknown type ("+g+").";};c.prototype.Gb=function(g){var m=this;Object.keys(g).forEach(function(r){var w=ca(m.La,r);0!==w&&m.qb(g[r],w)});return!0};c.prototype.Fb=function(g){for(var m=0;m<g.length;m+=1)this.qb(g[m],m+1);return!0};c.prototype.reset=function(){this.freemem();return 0===Mc(this.La)&&0===Lc(this.La)};c.prototype.freemem=
function(){for(var g;void 0!==(g=this.fb.pop());)da(g)};c.prototype.free=function(){this.freemem();var g=0===Nc(this.La);delete this.db.ab[this.La];this.La=0;return g};d.prototype.next=function(){if(null===this.Za)return{done:!0};null!==this.Va&&(this.Va.free(),this.Va=null);if(!this.db.db)throw this.gb(),Error("Database closed");var g=ma(),m=v(4);na(h);na(m);try{this.db.handleError(G(this.db.db,this.eb,-1,h,m));this.eb=l(m,"i32");var r=l(h,"i32");if(0===r)return this.gb(),{done:!0};this.Va=new c(r,
this.db);this.db.ab[r]=this.Va;return{value:this.Va,done:!1}}catch(w){throw this.jb=C(this.eb),this.gb(),w;}finally{oa(g)}};d.prototype.gb=function(){da(this.Za);this.Za=null};d.prototype.getRemainingSQL=function(){return null!==this.jb?this.jb:C(this.eb)};"function"===typeof Symbol&&"symbol"===typeof Symbol.iterator&&(d.prototype[Symbol.iterator]=function(){return this});f.prototype.run=function(g,m){if(!this.db)throw"Database closed";if(m){g=this.prepare(g,m);try{g.step()}finally{g.free()}}else this.handleError(p(this.db,
g,0,0,h));return this};f.prototype.exec=function(g,m,r){if(!this.db)throw"Database closed";var w=ma(),y=null;try{var A=ea(g)+1,U=v(A);ha(g,t,U,A);var N=U;var O=v(4);for(g=[];0!==l(N,"i8");){na(h);na(O);this.handleError(G(this.db,N,-1,h,O));var P=l(h,"i32");N=l(O,"i32");if(0!==P){A=null;y=new c(P,this);for(null!=m&&y.bind(m);y.step();)null===A&&(A={columns:y.getColumnNames(),values:[]},g.push(A)),A.values.push(y.get(null,r));y.free()}}return g}catch(ya){throw y&&y.free(),ya;}finally{oa(w)}};f.prototype.each=
function(g,m,r,w,y){"function"===typeof m&&(w=r,r=m,m=void 0);g=this.prepare(g,m);try{for(;g.step();)r(g.getAsObject(null,y))}finally{g.free()}if("function"===typeof w)return w()};f.prototype.prepare=function(g,m){na(h);this.handleError(q(this.db,g,-1,h,0));g=l(h,"i32");if(0===g)throw"Nothing to prepare";var r=new c(g,this);null!=m&&r.bind(m);return this.ab[g]=r};f.prototype.iterateStatements=function(g){return new d(g,this)};f.prototype["export"]=function(){Object.values(this.ab).forEach(function(m){m.free()});
Object.values(this.Na).forEach(pa);this.Na={};this.handleError(x(this.db));var g=qa(this.filename);this.handleError(n(this.filename,h));this.db=l(h,"i32");return g};f.prototype.close=function(){null!==this.db&&(Object.values(this.ab).forEach(function(g){g.free()}),Object.values(this.Na).forEach(pa),this.Na={},this.handleError(x(this.db)),ra("/"+this.filename),this.db=null)};f.prototype.handleError=function(g){if(0===g)return null;g=L(this.db);throw Error(g);};f.prototype.getRowsModified=function(){return z(this.db)};
f.prototype.create_function=function(g,m){Object.prototype.hasOwnProperty.call(this.Na,g)&&(pa(this.Na[g]),delete this.Na[g]);var r=sa(function(w,y,A){y=b(y,A);try{var U=m.apply(null,y)}catch(N){La(w,N,-1);return}a(w,U)},"viii");this.Na[g]=r;this.handleError(Db(this.db,g,m.length,1,0,r,0,0,0));return this};f.prototype.create_aggregate=function(g,m){var r=m.init||function(){return null},w=m.finalize||function(O){return O},y=m.step;if(!y)throw"An aggregate function must have a step function in "+g;
var A={};Object.hasOwnProperty.call(this.Na,g)&&(pa(this.Na[g]),delete this.Na[g]);m=g+"__finalize";Object.hasOwnProperty.call(this.Na,m)&&(pa(this.Na[m]),delete this.Na[m]);var U=sa(function(O,P,ya){var la=Eb(O,1);Object.hasOwnProperty.call(A,la)||(A[la]=r());P=b(P,ya);P=[A[la]].concat(P);try{A[la]=y.apply(null,P)}catch(Pc){delete A[la],La(O,Pc,-1)}},"viii"),N=sa(function(O){var P=Eb(O,1);try{var ya=w(A[P])}catch(la){delete A[P];La(O,la,-1);return}a(O,ya);delete A[P]},"vi");this.Na[g]=U;this.Na[m]=
N;this.handleError(Db(this.db,g,y.length-1,1,0,0,U,N,0));return this};e.Database=f};var ta=Object.assign({},e),ua="./this.program",va="object"==typeof window,wa="function"==typeof importScripts,xa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,D="",za,Aa,Ba,fs,Ca,Da;
if(xa)D=wa?require("path").dirname(D)+"/":__dirname+"/",Da=()=>{Ca||(fs=require("fs"),Ca=require("path"))},za=function(a,b){Da();a=Ca.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")},Ba=a=>{a=za(a,!0);a.buffer||(a=new Uint8Array(a));return a},Aa=(a,b,c)=>{Da();a=Ca.normalize(a);fs.readFile(a,function(d,f){d?c(d):b(f.buffer)})},1<process.argv.length&&(ua=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),"undefined"!=typeof module&&(module.exports=e),e.inspect=function(){return"[Emscripten Module object]"};
else if(va||wa)wa?D=self.location.href:"undefined"!=typeof document&&document.currentScript&&(D=document.currentScript.src),D=0!==D.indexOf("blob:")?D.substr(0,D.replace(/[?#].*/,"").lastIndexOf("/")+1):"",za=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},wa&&(Ba=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),Aa=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";
d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var Ea=e.print||console.log.bind(console),Fa=e.printErr||console.warn.bind(console);Object.assign(e,ta);ta=null;e.thisProgram&&(ua=e.thisProgram);var Ga;e.wasmBinary&&(Ga=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!=typeof WebAssembly&&Ha("no native wasm support detected");var Ia,Ja=!1,Ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|k:(f&7)<<18|h<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function C(a,b){return a?Ma(u,a,b):""}
function ha(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var h=0;h<a.length;++h){var k=a.charCodeAt(h);if(55296<=k&&57343>=k){var n=a.charCodeAt(++h);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f}
function ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var Na,t,u,Oa,E,F,Pa,Qa;function Ra(){var a=Ia.buffer;Na=a;e.HEAP8=t=new Int8Array(a);e.HEAP16=Oa=new Int16Array(a);e.HEAP32=E=new Int32Array(a);e.HEAPU8=u=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAPU32=F=new Uint32Array(a);e.HEAPF32=Pa=new Float32Array(a);e.HEAPF64=Qa=new Float64Array(a)}var Sa,Ta=[],Ua=[],Va=[];
function Wa(){var a=e.preRun.shift();Ta.unshift(a)}var Xa=0,Ya=null,Za=null;function $a(){Xa++;e.monitorRunDependencies&&e.monitorRunDependencies(Xa)}function ab(){Xa--;e.monitorRunDependencies&&e.monitorRunDependencies(Xa);if(0==Xa&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za)){var a=Za;Za=null;a()}}function Ha(a){if(e.onAbort)e.onAbort(a);a="Aborted("+a+")";Fa(a);Ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function bb(){return K.startsWith("data:application/octet-stream;base64,")}var K;K="sql-wasm.wasm";if(!bb()){var db=K;K=e.locateFile?e.locateFile(db,D):D+db}function eb(){var a=K;try{if(a==K&&Ga)return new Uint8Array(Ga);if(Ba)return Ba(a);throw"both async and sync fetching of the wasm failed";}catch(b){Ha(b)}}
function fb(){if(!Ga&&(va||wa)){if("function"==typeof fetch&&!K.startsWith("file://"))return fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return eb()});if(Aa)return new Promise(function(a,b){Aa(K,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return eb()})}var M,Q;function gb(a){for(;0<a.length;)a.shift()(e)}
function l(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return t[a>>0];case "i8":return t[a>>0];case "i16":return Oa[a>>1];case "i32":return E[a>>2];case "i64":return E[a>>2];case "float":return Pa[a>>2];case "double":return Qa[a>>3];case "*":return F[a>>2];default:Ha("invalid type for getValue: "+b)}return null}
function na(a){var b="i32";b.endsWith("*")&&(b="*");switch(b){case "i1":t[a>>0]=0;break;case "i8":t[a>>0]=0;break;case "i16":Oa[a>>1]=0;break;case "i32":E[a>>2]=0;break;case "i64":Q=[0,(M=0,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[a>>2]=Q[0];E[a+4>>2]=Q[1];break;case "float":Pa[a>>2]=0;break;case "double":Qa[a>>3]=0;break;case "*":F[a>>2]=0;break;default:Ha("invalid type for setValue: "+b)}}
var hb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},R=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=hb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ib=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},jb=a=>{if("/"===
a)return"/";a=R(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)};function kb(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}if(xa)try{var b=require("crypto");return()=>b.randomBytes(1)[0]}catch(c){}return()=>Ha("randomDevice")}
function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=hb(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}function ja(a,b){var c=Array(ea(a)+1);a=ha(a,c,0,c.length);b&&(c.length=a);return c}var mb=[];function nb(a,b){mb[a]={input:[],output:[],Ya:b};ob(a,pb)}
var pb={open:function(a){var b=mb[a.node.rdev];if(!b)throw new S(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ya.fsync(a.tty)},fsync:function(a){a.tty.Ya.fsync(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ya.wb)throw new S(60);for(var f=0,h=0;h<d;h++){try{var k=a.tty.Ya.wb(a.tty)}catch(n){throw new S(29);}if(void 0===k&&0===f)throw new S(6);if(null===k||void 0===k)break;f++;b[c+h]=k}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Ya.kb)throw new S(60);
try{for(var f=0;f<d;f++)a.tty.Ya.kb(a.tty,b[c+f])}catch(h){throw new S(29);}d&&(a.node.timestamp=Date.now());return f}},qb={wb:function(a){if(!a.input.length){var b=null;if(xa){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,-1)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ja(b,!0)}return a.input.shift()},kb:function(a,b){null===b||10===b?(Ea(Ma(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(Ea(Ma(a.output,0)),a.output=[])}},rb={kb:function(a,b){null===b||10===b?(Fa(Ma(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync:function(a){a.output&&0<a.output.length&&(Fa(Ma(a.output,0)),a.output=[])}};
function sb(a){a=65536*Math.ceil(a/65536);var b=tb(65536,a);b?(u.fill(0,b,b+a),a=b):a=0;return a}
var T={Qa:null,Sa:function(){return T.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.Qa||(T.Qa={dir:{node:{Pa:T.Ga.Pa,Oa:T.Ga.Oa,lookup:T.Ga.lookup,bb:T.Ga.bb,rename:T.Ga.rename,unlink:T.Ga.unlink,rmdir:T.Ga.rmdir,readdir:T.Ga.readdir,symlink:T.Ga.symlink},stream:{Ua:T.Ia.Ua}},file:{node:{Pa:T.Ga.Pa,Oa:T.Ga.Oa},stream:{Ua:T.Ia.Ua,read:T.Ia.read,write:T.Ia.write,mb:T.Ia.mb,$a:T.Ia.$a,cb:T.Ia.cb}},link:{node:{Pa:T.Ga.Pa,Oa:T.Ga.Oa,
readlink:T.Ga.readlink},stream:{}},sb:{node:{Pa:T.Ga.Pa,Oa:T.Ga.Oa},stream:ub}});c=vb(a,b,c,d);16384===(c.mode&61440)?(c.Ga=T.Qa.dir.node,c.Ia=T.Qa.dir.stream,c.Ha={}):32768===(c.mode&61440)?(c.Ga=T.Qa.file.node,c.Ia=T.Qa.file.stream,c.Ma=0,c.Ha=null):40960===(c.mode&61440)?(c.Ga=T.Qa.link.node,c.Ia=T.Qa.link.stream):8192===(c.mode&61440)&&(c.Ga=T.Qa.sb.node,c.Ia=T.Qa.sb.stream);c.timestamp=Date.now();a&&(a.Ha[b]=c,a.timestamp=c.timestamp);return c},Sb:function(a){return a.Ha?a.Ha.subarray?a.Ha.subarray(0,
a.Ma):new Uint8Array(a.Ha):new Uint8Array(0)},tb:function(a,b){var c=a.Ha?a.Ha.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ha,a.Ha=new Uint8Array(b),0<a.Ma&&a.Ha.set(c.subarray(0,a.Ma),0))},Pb:function(a,b){if(a.Ma!=b)if(0==b)a.Ha=null,a.Ma=0;else{var c=a.Ha;a.Ha=new Uint8Array(b);c&&a.Ha.set(c.subarray(0,Math.min(b,a.Ma)));a.Ma=b}},Ga:{Pa:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;
16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ma:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ib=4096;b.blocks=Math.ceil(b.size/b.Ib);return b},Oa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.Pb(a,b.size)},lookup:function(){throw wb[44];},bb:function(a,b,c,d){return T.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===
(a.mode&61440)){try{var d=xb(b,c)}catch(h){}if(d)for(var f in d.Ha)throw new S(55);}delete a.parent.Ha[a.name];a.parent.timestamp=Date.now();a.name=c;b.Ha[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Ha[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=xb(a,b),d;for(d in c.Ha)throw new S(55);delete a.Ha[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Ha)a.Ha.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=T.createNode(a,
b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},Ia:{read:function(a,b,c,d,f){var h=a.node.Ha;if(f>=a.node.Ma)return 0;a=Math.min(a.node.Ma-f,d);if(8<a&&h.subarray)b.set(h.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=h[f+d];return a},write:function(a,b,c,d,f,h){b.buffer===t.buffer&&(h=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ha||a.Ha.subarray)){if(h)return a.Ha=b.subarray(c,c+d),a.Ma=d;if(0===a.Ma&&0===f)return a.Ha=
b.slice(c,c+d),a.Ma=d;if(f+d<=a.Ma)return a.Ha.set(b.subarray(c,c+d),f),d}T.tb(a,f+d);if(a.Ha.subarray&&b.subarray)a.Ha.set(b.subarray(c,c+d),f);else for(h=0;h<d;h++)a.Ha[f+h]=b[c+h];a.Ma=Math.max(a.Ma,f+d);return d},Ua:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ma);if(0>b)throw new S(28);return b},mb:function(a,b,c){T.tb(a.node,b+c);a.node.Ma=Math.max(a.node.Ma,b+c)},$a:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new S(43);a=a.node.Ha;if(f&2||
a.buffer!==Na){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=sb(b);if(!b)throw new S(48);t.set(a,b)}else c=!1,b=a.byteOffset;return{Ab:b,nb:c}},cb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new S(43);if(f&2)return 0;T.Ia.write(a,b,0,d,c,!1);return 0}}};
function yb(a,b,c){var d="al "+a;Aa(a,f=>{f||Ha('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(f));d&&ab(d)},()=>{if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&$a(d)}
var zb=null,Ab={},Fb=[],Gb=1,Hb=null,Ib=!0,S=null,wb={},V=(a,b={})=>{a=lb("/",a);if(!a)return{path:"",node:null};b=Object.assign({ub:!0,lb:0},b);if(8<b.lb)throw new S(32);a=hb(a.split("/").filter(k=>!!k),!1);for(var c=zb,d="/",f=0;f<a.length;f++){var h=f===a.length-1;if(h&&b.parent)break;c=xb(c,a[f]);d=R(d+"/"+a[f]);c.Wa&&(!h||h&&b.ub)&&(c=c.Wa.root);if(!h||b.Ta)for(h=0;40960===(c.mode&61440);)if(c=Jb(d),d=lb(ib(d),c),c=V(d,{lb:b.lb+1}).node,40<h++)throw new S(32);}return{path:d,node:c}},Kb=a=>{for(var b;;){if(a===
a.parent)return a=a.Sa.zb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}},Lb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Hb.length},Mb=a=>{var b=Lb(a.parent.id,a.name);if(Hb[b]===a)Hb[b]=a.Xa;else for(b=Hb[b];b;){if(b.Xa===a){b.Xa=a.Xa;break}b=b.Xa}},xb=(a,b)=>{var c;if(c=(c=Nb(a,"x"))?c:a.Ga.lookup?0:2)throw new S(c,a);for(c=Hb[Lb(a.id,b)];c;c=c.Xa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ga.lookup(a,b)},vb=(a,b,
c,d)=>{a=new Ob(a,b,c,d);b=Lb(a.parent.id,a.name);a.Xa=Hb[b];return Hb[b]=a},Pb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090},Qb=a=>{var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Nb=(a,b)=>{if(Ib)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Rb=(a,b)=>{try{return xb(a,b),20}catch(c){}return Nb(a,"wx")},Sb=(a,b,c)=>{try{var d=xb(a,b)}catch(f){return f.Ka}if(a=Nb(a,"wx"))return a;if(c){if(16384!==(d.mode&
61440))return 54;if(d===d.parent||"/"===Kb(d))return 10}else if(16384===(d.mode&61440))return 31;return 0},Tb=(a=0)=>{for(;4096>=a;a++)if(!Fb[a])return a;throw new S(33);},Vb=(a,b)=>{Ub||(Ub=function(){this.Ra={}},Ub.prototype={},Object.defineProperties(Ub.prototype,{object:{get:function(){return this.node},set:function(c){this.node=c}},flags:{get:function(){return this.Ra.flags},set:function(c){this.Ra.flags=c}},position:{get:function(){return this.Ra.position},set:function(c){this.Ra.position=c}}}));
a=Object.assign(new Ub,a);b=Tb(b);a.fd=b;return Fb[b]=a},ub={open:a=>{a.Ia=Ab[a.node.rdev].Ia;a.Ia.open&&a.Ia.open(a)},Ua:()=>{throw new S(70);}},ob=(a,b)=>{Ab[a]={Ia:b}},Wb=(a,b)=>{var c="/"===b,d=!b;if(c&&zb)throw new S(10);if(!c&&!d){var f=V(b,{ub:!1});b=f.path;f=f.node;if(f.Wa)throw new S(10);if(16384!==(f.mode&61440))throw new S(54);}b={type:a,Ub:{},zb:b,Ob:[]};a=a.Sa(b);a.Sa=b;b.root=a;c?zb=a:f&&(f.Wa=b,f.Sa&&f.Sa.Ob.push(b))},Xb=(a,b,c)=>{var d=V(a,{parent:!0}).node;a=jb(a);if(!a||"."===a||
".."===a)throw new S(28);var f=Rb(d,a);if(f)throw new S(f);if(!d.Ga.bb)throw new S(63);return d.Ga.bb(d,a,b,c)},W=(a,b)=>Xb(a,(void 0!==b?b:511)&1023|16384,0),Yb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return Xb(a,b|8192,c)},Zb=(a,b)=>{if(!lb(a))throw new S(44);var c=V(b,{parent:!0}).node;if(!c)throw new S(44);b=jb(b);var d=Rb(c,b);if(d)throw new S(d);if(!c.Ga.symlink)throw new S(63);c.Ga.symlink(c,b,a)},$b=a=>{var b=V(a,{parent:!0}).node;a=jb(a);var c=xb(b,a),d=Sb(b,a,!0);if(d)throw new S(d);
if(!b.Ga.rmdir)throw new S(63);if(c.Wa)throw new S(10);b.Ga.rmdir(b,a);Mb(c)},ra=a=>{var b=V(a,{parent:!0}).node;if(!b)throw new S(44);a=jb(a);var c=xb(b,a),d=Sb(b,a,!1);if(d)throw new S(d);if(!b.Ga.unlink)throw new S(63);if(c.Wa)throw new S(10);b.Ga.unlink(b,a);Mb(c)},Jb=a=>{a=V(a).node;if(!a)throw new S(44);if(!a.Ga.readlink)throw new S(28);return lb(Kb(a.parent),a.Ga.readlink(a))},ac=(a,b)=>{a=V(a,{Ta:!b}).node;if(!a)throw new S(44);if(!a.Ga.Pa)throw new S(63);return a.Ga.Pa(a)},bc=a=>ac(a,!0),
cc=(a,b)=>{a="string"==typeof a?V(a,{Ta:!0}).node:a;if(!a.Ga.Oa)throw new S(63);a.Ga.Oa(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},dc=(a,b)=>{if(0>b)throw new S(28);a="string"==typeof a?V(a,{Ta:!0}).node:a;if(!a.Ga.Oa)throw new S(63);if(16384===(a.mode&61440))throw new S(31);if(32768!==(a.mode&61440))throw new S(28);var c=Nb(a,"w");if(c)throw new S(c);a.Ga.Oa(a,{size:b,timestamp:Date.now()})},fc=(a,b,c)=>{if(""===a)throw new S(44);if("string"==typeof b){var d=Pb[b];if("undefined"==typeof d)throw Error("Unknown file open mode: "+
b);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=R(a);try{f=V(a,{Ta:!(b&131072)}).node}catch(h){}}d=!1;if(b&64)if(f){if(b&128)throw new S(20);}else f=Xb(a,c,0),d=!0;if(!f)throw new S(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new S(54);if(!d&&(c=f?40960===(f.mode&61440)?32:16384===(f.mode&61440)&&("r"!==Qb(b)||b&512)?31:Nb(f,Qb(b)):44))throw new S(c);b&512&&!d&&dc(f,0);b&=-131713;f=Vb({node:f,path:Kb(f),flags:b,seekable:!0,
position:0,Ia:f.Ia,Rb:[],error:!1});f.Ia.open&&f.Ia.open(f);!e.logReadFiles||b&1||(ec||(ec={}),a in ec||(ec[a]=1));return f},gc=a=>{if(null===a.fd)throw new S(8);a.hb&&(a.hb=null);try{a.Ia.close&&a.Ia.close(a)}catch(b){throw b;}finally{Fb[a.fd]=null}a.fd=null},hc=(a,b,c)=>{if(null===a.fd)throw new S(8);if(!a.seekable||!a.Ia.Ua)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.Ia.Ua(a,b,c);a.Rb=[]},ic=(a,b,c,d,f)=>{if(0>d||0>f)throw new S(28);if(null===a.fd)throw new S(8);if(1===(a.flags&
2097155))throw new S(8);if(16384===(a.node.mode&61440))throw new S(31);if(!a.Ia.read)throw new S(28);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new S(70);b=a.Ia.read(a,b,c,d,f);h||(a.position+=b);return b},jc=(a,b,c,d,f,h)=>{if(0>d||0>f)throw new S(28);if(null===a.fd)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(16384===(a.node.mode&61440))throw new S(31);if(!a.Ia.write)throw new S(28);a.seekable&&a.flags&1024&&hc(a,0,2);var k="undefined"!=typeof f;if(!k)f=
a.position;else if(!a.seekable)throw new S(70);b=a.Ia.write(a,b,c,d,f,h);k||(a.position+=b);return b},qa=a=>{var b="binary";if("utf8"!==b&&"binary"!==b)throw Error('Invalid encoding type "'+b+'"');var c;var d=fc(a,d||0);a=ac(a).size;var f=new Uint8Array(a);ic(d,f,0,a,0);"utf8"===b?c=Ma(f,0):"binary"===b&&(c=f);gc(d);return c},kc=()=>{S||(S=function(a,b){this.node=b;this.Qb=function(c){this.Ka=c};this.Qb(a);this.message="FS error"},S.prototype=Error(),S.prototype.constructor=S,[44].forEach(a=>{wb[a]=
new S(a);wb[a].stack="<generic error, no stack>"}))},lc,mc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},nc=(a,b)=>{a="string"==typeof a?a:Kb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=R(a+"/"+c);try{W(d)}catch(f){}a=d}}return d},oc=(a,b,c,d)=>{a=R(("string"==typeof a?a:Kb(a))+"/"+b);c=mc(c,d);return Xb(a,(void 0!==c?c:438)&4095|32768,0)},ia=(a,b,c,d,f,h)=>{var k=b;a&&(a="string"==typeof a?a:Kb(a),k=b?R(a+"/"+b):a);a=mc(d,f);k=Xb(k,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==
typeof c){b=Array(c.length);d=0;for(f=c.length;d<f;++d)b[d]=c.charCodeAt(d);c=b}cc(k,a|146);b=fc(k,577);jc(b,c,0,c.length,0,h);gc(b);cc(k,a)}return k},X=(a,b,c,d)=>{a=R(("string"==typeof a?a:Kb(a))+"/"+b);b=mc(!!c,!!d);X.yb||(X.yb=64);var f=X.yb++<<8|0;ob(f,{open:h=>{h.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(h,k,n,x)=>{for(var p=0,z=0;z<x;z++){try{var q=c()}catch(B){throw new S(29);}if(void 0===q&&0===p)throw new S(6);if(null===q||void 0===q)break;p++;k[n+z]=q}p&&(h.node.timestamp=
Date.now());return p},write:(h,k,n,x)=>{for(var p=0;p<x;p++)try{d(k[n+p])}catch(z){throw new S(29);}x&&(h.node.timestamp=Date.now());return p}});return Yb(a,b,f)},pc=a=>{if(!(a.Mb||a.Nb||a.link||a.Ha)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(za)try{a.Ha=ja(za(a.url),!0),a.Ma=a.Ha.length}catch(b){throw new S(29);
}else throw Error("Cannot load without read() or XMLHttpRequest.");}},qc=(a,b,c,d,f)=>{function h(){this.ib=!1;this.Ra=[]}function k(q,B,H,G,I){q=q.node.Ha;if(I>=q.length)return 0;G=Math.min(q.length-I,G);if(q.slice)for(var J=0;J<G;J++)B[H+J]=q[I+J];else for(J=0;J<G;J++)B[H+J]=q.get(I+J);return G}h.prototype.get=function(q){if(!(q>this.length-1||0>q)){var B=q%this.chunkSize;return this.xb(q/this.chunkSize|0)[B]}};h.prototype.Bb=function(q){this.xb=q};h.prototype.rb=function(){var q=new XMLHttpRequest;
q.open("HEAD",c,!1);q.send(null);if(!(200<=q.status&&300>q.status||304===q.status))throw Error("Couldn't load "+c+". Status: "+q.status);var B=Number(q.getResponseHeader("Content-length")),H,G=(H=q.getResponseHeader("Accept-Ranges"))&&"bytes"===H;q=(H=q.getResponseHeader("Content-Encoding"))&&"gzip"===H;var I=1048576;G||(I=B);var J=this;J.Bb(ba=>{var ka=ba*I,ca=(ba+1)*I-1;ca=Math.min(ca,B-1);if("undefined"==typeof J.Ra[ba]){var cb=J.Ra;if(ka>ca)throw Error("invalid range ("+ka+", "+ca+") or no bytes requested!");
if(ca>B-1)throw Error("only "+B+" bytes available! programmer error!");var L=new XMLHttpRequest;L.open("GET",c,!1);B!==I&&L.setRequestHeader("Range","bytes="+ka+"-"+ca);L.responseType="arraybuffer";L.overrideMimeType&&L.overrideMimeType("text/plain; charset=x-user-defined");L.send(null);if(!(200<=L.status&&300>L.status||304===L.status))throw Error("Couldn't load "+c+". Status: "+L.status);ka=void 0!==L.response?new Uint8Array(L.response||[]):ja(L.responseText||"",!0);cb[ba]=ka}if("undefined"==typeof J.Ra[ba])throw Error("doXHR failed!");
return J.Ra[ba]});if(q||!B)I=B=1,I=B=this.xb(0).length,Ea("LazyFiles on gzip forces download of the whole file when length is accessed");this.Db=B;this.Cb=I;this.ib=!0};if("undefined"!=typeof XMLHttpRequest){if(!wa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var n=new h;Object.defineProperties(n,{length:{get:function(){this.ib||this.rb();return this.Db}},chunkSize:{get:function(){this.ib||this.rb();return this.Cb}}});var x=
void 0}else x=c,n=void 0;var p=oc(a,b,d,f);n?p.Ha=n:x&&(p.Ha=null,p.url=x);Object.defineProperties(p,{Ma:{get:function(){return this.Ha.length}}});var z={};Object.keys(p.Ia).forEach(q=>{var B=p.Ia[q];z[q]=function(){pc(p);return B.apply(null,arguments)}});z.read=(q,B,H,G,I)=>{pc(p);return k(q,B,H,G,I)};z.$a=(q,B,H)=>{pc(p);var G=sb(B);if(!G)throw new S(48);k(q,t,G,B,H);return{Ab:G,nb:!0}};p.Ia=z;return p},sc=(a,b,c,d,f,h,k,n,x,p)=>{function z(H){function G(I){p&&p();n||ia(a,b,I,d,f,x);h&&h();ab(B)}
rc.Tb(H,q,G,()=>{k&&k();ab(B)})||G(H)}var q=b?lb(R(a+"/"+b)):a,B="cp "+q;$a(B);"string"==typeof c?yb(c,H=>z(H),k):z(c)},Y={},Ub,ec;function tc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Z(a).path;if(0==b.length){if(!c)throw new S(44);return a}return R(a+"/"+b)}
function Oc(a,b,c){try{var d=a(b)}catch(f){if(f&&f.node&&R(b)!==R(Kb(f.node)))return-54;throw f;}E[c>>2]=d.dev;E[c+8>>2]=d.ino;E[c+12>>2]=d.mode;F[c+16>>2]=d.nlink;E[c+20>>2]=d.uid;E[c+24>>2]=d.gid;E[c+28>>2]=d.rdev;Q=[d.size>>>0,(M=d.size,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[c+40>>2]=Q[0];E[c+44>>2]=Q[1];E[c+48>>2]=4096;E[c+52>>2]=d.blocks;Q=[Math.floor(d.atime.getTime()/1E3)>>>0,(M=Math.floor(d.atime.getTime()/
1E3),1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[c+56>>2]=Q[0];E[c+60>>2]=Q[1];F[c+64>>2]=0;Q=[Math.floor(d.mtime.getTime()/1E3)>>>0,(M=Math.floor(d.mtime.getTime()/1E3),1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[c+72>>2]=Q[0];E[c+76>>2]=Q[1];F[c+80>>2]=0;Q=[Math.floor(d.ctime.getTime()/1E3)>>>0,(M=Math.floor(d.ctime.getTime()/1E3),1<=+Math.abs(M)?
0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[c+88>>2]=Q[0];E[c+92>>2]=Q[1];F[c+96>>2]=0;Q=[d.ino>>>0,(M=d.ino,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[c+104>>2]=Q[0];E[c+108>>2]=Q[1];return 0}var Qc=void 0;function Rc(){Qc+=4;return E[Qc-4>>2]}function Z(a){a=Fb[a];if(!a)throw new S(8);return a}function Sc(a){return F[a>>2]+4294967296*E[a+4>>2]}
function Tc(a){var b=ea(a)+1,c=fa(b);c&&ha(a,t,c,b);return c}function Uc(a,b,c){function d(x){return(x=x.toTimeString().match(/\(([A-Za-z ]+)\)$/))?x[1]:"GMT"}var f=(new Date).getFullYear(),h=new Date(f,0,1),k=new Date(f,6,1);f=h.getTimezoneOffset();var n=k.getTimezoneOffset();E[a>>2]=60*Math.max(f,n);E[b>>2]=Number(f!=n);a=d(h);b=d(k);a=Tc(a);b=Tc(b);n<f?(F[c>>2]=a,F[c+4>>2]=b):(F[c>>2]=b,F[c+4>>2]=a)}function Vc(a,b,c){Vc.Jb||(Vc.Jb=!0,Uc(a,b,c))}var Wc;
Wc=xa?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();var Xc={};function Yc(){if(!Zc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ua||"./this.program"},b;for(b in Xc)void 0===Xc[b]?delete a[b]:a[b]=Xc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Zc=c}return Zc}var Zc,$c=void 0,ad=[];
function sa(a,b){if(!$c){$c=new WeakMap;var c=Sa.length;if($c)for(var d=0;d<0+c;d++){var f=Sa.get(d);f&&$c.set(f,d)}}if($c.has(a))return $c.get(a);if(ad.length)c=ad.pop();else{try{Sa.grow(1)}catch(n){if(!(n instanceof RangeError))throw n;throw"Unable to grow wasm table. Set ALLOW_TABLE_GROWTH.";}c=Sa.length-1}try{Sa.set(c,a)}catch(n){if(!(n instanceof TypeError))throw n;if("function"==typeof WebAssembly.Function){d=WebAssembly.Function;f={i:"i32",j:"i64",f:"f32",d:"f64",p:"i32"};for(var h={parameters:[],
results:"v"==b[0]?[]:[f[b[0]]]},k=1;k<b.length;++k)h.parameters.push(f[b[k]]);b=new d(h,a)}else{d=[1,96];f=b.slice(0,1);b=b.slice(1);h={i:127,p:127,j:126,f:125,d:124};k=b.length;128>k?d.push(k):d.push(k%128|128,k>>7);for(k=0;k<b.length;++k)d.push(h[b[k]]);"v"==f?d.push(0):d.push(1,h[f]);b=[0,97,115,109,1,0,0,0,1];f=d.length;128>f?b.push(f):b.push(f%128|128,f>>7);b.push.apply(b,d);b.push(2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(new Uint8Array(b));b=(new WebAssembly.Instance(b,
{e:{f:a}})).exports.f}Sa.set(c,b)}$c.set(a,c);return c}function pa(a){$c.delete(Sa.get(a));ad.push(a)}var bd=0,cd=1;function aa(a){var b=bd==cd?v(a.length):fa(a.length);a.subarray||a.slice||(a=new Uint8Array(a));u.set(a,b);return b}
function dd(a,b,c,d){var f={string:p=>{var z=0;if(null!==p&&void 0!==p&&0!==p){var q=(p.length<<2)+1;z=v(q);ha(p,u,z,q)}return z},array:p=>{var z=v(p.length);t.set(p,z);return z}};a=e["_"+a];var h=[],k=0;if(d)for(var n=0;n<d.length;n++){var x=f[c[n]];x?(0===k&&(k=ma()),h[n]=x(d[n])):h[n]=d[n]}c=a.apply(null,h);return c=function(p){0!==k&&oa(k);return"string"===b?C(p):"boolean"===b?!!p:p}(c)}
function Ob(a,b,c,d){a||(a=this);this.parent=a;this.Sa=a.Sa;this.Wa=null;this.id=Gb++;this.name=b;this.mode=c;this.Ga={};this.Ia={};this.rdev=d}Object.defineProperties(Ob.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Nb:{get:function(){return 16384===(this.mode&61440)}},Mb:{get:function(){return 8192===(this.mode&61440)}}});kc();
Hb=Array(4096);Wb(T,"/");W("/tmp");W("/home");W("/home/web_user");(()=>{W("/dev");ob(259,{read:()=>0,write:(b,c,d,f)=>f});Yb("/dev/null",259);nb(1280,qb);nb(1536,rb);Yb("/dev/tty",1280);Yb("/dev/tty1",1536);var a=kb();X("/dev","random",a);X("/dev","urandom",a);W("/dev/shm");W("/dev/shm/tmp")})();
(()=>{W("/proc");var a=W("/proc/self");W("/proc/self/fd");Wb({Sa:()=>{var b=vb(a,"fd",16895,73);b.Ga={lookup:(c,d)=>{var f=Fb[+d];if(!f)throw new S(8);c={parent:null,Sa:{zb:"fake"},Ga:{readlink:()=>f.path}};return c.parent=c}};return b}},"/proc/self/fd")})();var rc;e.FS_createPath=nc;e.FS_createDataFile=ia;e.FS_createPreloadedFile=sc;e.FS_unlink=ra;e.FS_createLazyFile=qc;e.FS_createDevice=X;
var fd={a:function(a,b,c,d){Ha("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",c,d?C(d):"unknown function"])},h:function(a,b){try{return a=C(a),cc(a,b),0}catch(c){if("undefined"==typeof Y||!(c instanceof S))throw c;return-c.Ka}},H:function(a,b,c){try{b=C(b);b=tc(a,b);if(c&-8)return-28;var d=V(b,{Ta:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Nb(d,a)?-2:0}catch(f){if("undefined"==typeof Y||!(f instanceof S))throw f;return-f.Ka}},i:function(a,b){try{var c=
Fb[a];if(!c)throw new S(8);cc(c.node,b);return 0}catch(d){if("undefined"==typeof Y||!(d instanceof S))throw d;return-d.Ka}},g:function(a){try{var b=Fb[a];if(!b)throw new S(8);var c=b.node;var d="string"==typeof c?V(c,{Ta:!0}).node:c;if(!d.Ga.Oa)throw new S(63);d.Ga.Oa(d,{timestamp:Date.now()});return 0}catch(f){if("undefined"==typeof Y||!(f instanceof S))throw f;return-f.Ka}},b:function(a,b,c){Qc=c;try{var d=Z(a);switch(b){case 0:var f=Rc();return 0>f?-28:Vb(d,f).fd;case 1:case 2:return 0;case 3:return d.flags;
case 4:return f=Rc(),d.flags|=f,0;case 5:return f=Rc(),Oa[f+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return E[ed()>>2]=28,-1;default:return-28}}catch(h){if("undefined"==typeof Y||!(h instanceof S))throw h;return-h.Ka}},G:function(a,b){try{var c=Z(a);return Oc(ac,c.path,b)}catch(d){if("undefined"==typeof Y||!(d instanceof S))throw d;return-d.Ka}},l:function(a,b,c){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return-61;var d=Fb[a];if(!d)throw new S(8);
if(0===(d.flags&2097155))throw new S(28);dc(d.node,b);return 0}catch(f){if("undefined"==typeof Y||!(f instanceof S))throw f;return-f.Ka}},B:function(a,b){try{if(0===b)return-28;var c=ea("/")+1;if(b<c)return-68;ha("/",u,a,b);return c}catch(d){if("undefined"==typeof Y||!(d instanceof S))throw d;return-d.Ka}},E:function(a,b){try{return a=C(a),Oc(bc,a,b)}catch(c){if("undefined"==typeof Y||!(c instanceof S))throw c;return-c.Ka}},y:function(a,b,c){try{return b=C(b),b=tc(a,b),b=R(b),"/"===b[b.length-1]&&
(b=b.substr(0,b.length-1)),W(b,c),0}catch(d){if("undefined"==typeof Y||!(d instanceof S))throw d;return-d.Ka}},D:function(a,b,c,d){try{b=C(b);var f=d&256;b=tc(a,b,d&4096);return Oc(f?bc:ac,b,c)}catch(h){if("undefined"==typeof Y||!(h instanceof S))throw h;return-h.Ka}},v:function(a,b,c,d){Qc=d;try{b=C(b);b=tc(a,b);var f=d?Rc():0;return fc(b,c,f).fd}catch(h){if("undefined"==typeof Y||!(h instanceof S))throw h;return-h.Ka}},t:function(a,b,c,d){try{b=C(b);b=tc(a,b);if(0>=d)return-28;var f=Jb(b),h=Math.min(d,
ea(f)),k=t[c+h];ha(f,u,c,d+1);t[c+h]=k;return h}catch(n){if("undefined"==typeof Y||!(n instanceof S))throw n;return-n.Ka}},s:function(a){try{return a=C(a),$b(a),0}catch(b){if("undefined"==typeof Y||!(b instanceof S))throw b;return-b.Ka}},F:function(a,b){try{return a=C(a),Oc(ac,a,b)}catch(c){if("undefined"==typeof Y||!(c instanceof S))throw c;return-c.Ka}},p:function(a,b,c){try{return b=C(b),b=tc(a,b),0===c?ra(b):512===c?$b(b):Ha("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof Y||
!(d instanceof S))throw d;return-d.Ka}},o:function(a,b,c){try{b=C(b);b=tc(a,b,!0);if(c){var d=Sc(c),f=E[c+8>>2];h=1E3*d+f/1E6;c+=16;d=Sc(c);f=E[c+8>>2];k=1E3*d+f/1E6}else var h=Date.now(),k=h;a=h;var n=V(b,{Ta:!0}).node;n.Ga.Oa(n,{timestamp:Math.max(a,k)});return 0}catch(x){if("undefined"==typeof Y||!(x instanceof S))throw x;return-x.Ka}},e:function(){return Date.now()},j:function(a,b){a=new Date(1E3*Sc(a));E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();
E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);E[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();E[b+32>>2]=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0},w:function(a,b,c,d,f,h){try{var k=Z(d);if(0!==(b&2)&&0===(c&2)&&2!==(k.flags&2097155))throw new S(2);if(1===(k.flags&2097155))throw new S(2);if(!k.Ia.$a)throw new S(43);
var n=k.Ia.$a(k,a,f,b,c);var x=n.Ab;E[h>>2]=n.nb;return x}catch(p){if("undefined"==typeof Y||!(p instanceof S))throw p;return-p.Ka}},x:function(a,b,c,d,f,h){try{var k=Z(f);if(c&2){var n=u.slice(a,a+b);k&&k.Ia.cb&&k.Ia.cb(k,n,h,b,d)}}catch(x){if("undefined"==typeof Y||!(x instanceof S))throw x;return-x.Ka}},n:Vc,q:function(){return 2147483648},d:Wc,c:function(a){var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var f=Math;d=Math.max(a,
d);f=f.min.call(f,2147483648,d+(65536-d%65536)%65536);a:{try{Ia.grow(f-Na.byteLength+65535>>>16);Ra();var h=1;break a}catch(k){}h=void 0}if(h)return!0}return!1},z:function(a,b){var c=0;Yc().forEach(function(d,f){var h=b+c;f=F[a+4*f>>2]=h;for(h=0;h<d.length;++h)t[f++>>0]=d.charCodeAt(h);t[f>>0]=0;c+=d.length+1});return 0},A:function(a,b){var c=Yc();F[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});F[b>>2]=d;return 0},f:function(a){try{var b=Z(a);gc(b);return 0}catch(c){if("undefined"==
typeof Y||!(c instanceof S))throw c;return c.Ka}},m:function(a,b){try{var c=Z(a);t[b>>0]=c.tty?2:16384===(c.mode&61440)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){if("undefined"==typeof Y||!(d instanceof S))throw d;return d.Ka}},u:function(a,b,c,d){try{a:{var f=Z(a);a=b;for(var h=b=0;h<c;h++){var k=F[a>>2],n=F[a+4>>2];a+=8;var x=ic(f,t,k,n);if(0>x){var p=-1;break a}b+=x;if(x<n)break}p=b}F[d>>2]=p;return 0}catch(z){if("undefined"==typeof Y||!(z instanceof S))throw z;return z.Ka}},k:function(a,
b,c,d,f){try{b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;if(isNaN(b))return 61;var h=Z(a);hc(h,b,d);Q=[h.position>>>0,(M=h.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[f>>2]=Q[0];E[f+4>>2]=Q[1];h.hb&&0===b&&0===d&&(h.hb=null);return 0}catch(k){if("undefined"==typeof Y||!(k instanceof S))throw k;return k.Ka}},C:function(a){try{var b=Z(a);return b.Ia&&b.Ia.fsync?b.Ia.fsync(b):0}catch(c){if("undefined"==
typeof Y||!(c instanceof S))throw c;return c.Ka}},r:function(a,b,c,d){try{a:{var f=Z(a);a=b;for(var h=b=0;h<c;h++){var k=F[a>>2],n=F[a+4>>2];a+=8;var x=jc(f,t,k,n);if(0>x){var p=-1;break a}b+=x}p=b}F[d>>2]=p;return 0}catch(z){if("undefined"==typeof Y||!(z instanceof S))throw z;return z.Ka}}};
(function(){function a(f){e.asm=f.exports;Ia=e.asm.I;Ra();Sa=e.asm.Aa;Ua.unshift(e.asm.J);ab("wasm-instantiate")}function b(f){a(f.instance)}function c(f){return fb().then(function(h){return WebAssembly.instantiate(h,d)}).then(function(h){return h}).then(f,function(h){Fa("failed to asynchronously prepare wasm: "+h);Ha(h)})}var d={a:fd};$a("wasm-instantiate");if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return Fa("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return Ga||
"function"!=typeof WebAssembly.instantiateStreaming||bb()||K.startsWith("file://")||xa||"function"!=typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(h){Fa("wasm streaming compile failed: "+h);Fa("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.J).apply(null,arguments)};
e._sqlite3_free=function(){return(e._sqlite3_free=e.asm.K).apply(null,arguments)};e._sqlite3_value_double=function(){return(e._sqlite3_value_double=e.asm.L).apply(null,arguments)};e._sqlite3_value_text=function(){return(e._sqlite3_value_text=e.asm.M).apply(null,arguments)};var ed=e.___errno_location=function(){return(ed=e.___errno_location=e.asm.N).apply(null,arguments)};e._sqlite3_prepare_v2=function(){return(e._sqlite3_prepare_v2=e.asm.O).apply(null,arguments)};
e._sqlite3_step=function(){return(e._sqlite3_step=e.asm.P).apply(null,arguments)};e._sqlite3_finalize=function(){return(e._sqlite3_finalize=e.asm.Q).apply(null,arguments)};e._sqlite3_reset=function(){return(e._sqlite3_reset=e.asm.R).apply(null,arguments)};e._sqlite3_value_int=function(){return(e._sqlite3_value_int=e.asm.S).apply(null,arguments)};e._sqlite3_clear_bindings=function(){return(e._sqlite3_clear_bindings=e.asm.T).apply(null,arguments)};
e._sqlite3_value_blob=function(){return(e._sqlite3_value_blob=e.asm.U).apply(null,arguments)};e._sqlite3_value_bytes=function(){return(e._sqlite3_value_bytes=e.asm.V).apply(null,arguments)};e._sqlite3_value_type=function(){return(e._sqlite3_value_type=e.asm.W).apply(null,arguments)};e._sqlite3_result_blob=function(){return(e._sqlite3_result_blob=e.asm.X).apply(null,arguments)};e._sqlite3_result_double=function(){return(e._sqlite3_result_double=e.asm.Y).apply(null,arguments)};
e._sqlite3_result_error=function(){return(e._sqlite3_result_error=e.asm.Z).apply(null,arguments)};e._sqlite3_result_int=function(){return(e._sqlite3_result_int=e.asm._).apply(null,arguments)};e._sqlite3_result_int64=function(){return(e._sqlite3_result_int64=e.asm.$).apply(null,arguments)};e._sqlite3_result_null=function(){return(e._sqlite3_result_null=e.asm.aa).apply(null,arguments)};e._sqlite3_result_text=function(){return(e._sqlite3_result_text=e.asm.ba).apply(null,arguments)};
e._sqlite3_sql=function(){return(e._sqlite3_sql=e.asm.ca).apply(null,arguments)};e._sqlite3_aggregate_context=function(){return(e._sqlite3_aggregate_context=e.asm.da).apply(null,arguments)};e._sqlite3_column_count=function(){return(e._sqlite3_column_count=e.asm.ea).apply(null,arguments)};e._sqlite3_data_count=function(){return(e._sqlite3_data_count=e.asm.fa).apply(null,arguments)};e._sqlite3_column_blob=function(){return(e._sqlite3_column_blob=e.asm.ga).apply(null,arguments)};
e._sqlite3_column_bytes=function(){return(e._sqlite3_column_bytes=e.asm.ha).apply(null,arguments)};e._sqlite3_column_double=function(){return(e._sqlite3_column_double=e.asm.ia).apply(null,arguments)};e._sqlite3_column_text=function(){return(e._sqlite3_column_text=e.asm.ja).apply(null,arguments)};e._sqlite3_column_type=function(){return(e._sqlite3_column_type=e.asm.ka).apply(null,arguments)};e._sqlite3_column_name=function(){return(e._sqlite3_column_name=e.asm.la).apply(null,arguments)};
e._sqlite3_bind_blob=function(){return(e._sqlite3_bind_blob=e.asm.ma).apply(null,arguments)};e._sqlite3_bind_double=function(){return(e._sqlite3_bind_double=e.asm.na).apply(null,arguments)};e._sqlite3_bind_int=function(){return(e._sqlite3_bind_int=e.asm.oa).apply(null,arguments)};e._sqlite3_bind_text=function(){return(e._sqlite3_bind_text=e.asm.pa).apply(null,arguments)};e._sqlite3_bind_parameter_index=function(){return(e._sqlite3_bind_parameter_index=e.asm.qa).apply(null,arguments)};
e._sqlite3_normalized_sql=function(){return(e._sqlite3_normalized_sql=e.asm.ra).apply(null,arguments)};e._sqlite3_errmsg=function(){return(e._sqlite3_errmsg=e.asm.sa).apply(null,arguments)};e._sqlite3_exec=function(){return(e._sqlite3_exec=e.asm.ta).apply(null,arguments)};e._sqlite3_changes=function(){return(e._sqlite3_changes=e.asm.ua).apply(null,arguments)};e._sqlite3_close_v2=function(){return(e._sqlite3_close_v2=e.asm.va).apply(null,arguments)};
e._sqlite3_create_function_v2=function(){return(e._sqlite3_create_function_v2=e.asm.wa).apply(null,arguments)};e._sqlite3_open=function(){return(e._sqlite3_open=e.asm.xa).apply(null,arguments)};var da=e._free=function(){return(da=e._free=e.asm.ya).apply(null,arguments)},fa=e._malloc=function(){return(fa=e._malloc=e.asm.za).apply(null,arguments)};e._RegisterExtensionFunctions=function(){return(e._RegisterExtensionFunctions=e.asm.Ba).apply(null,arguments)};
var tb=e._emscripten_builtin_memalign=function(){return(tb=e._emscripten_builtin_memalign=e.asm.Ca).apply(null,arguments)},ma=e.stackSave=function(){return(ma=e.stackSave=e.asm.Da).apply(null,arguments)},oa=e.stackRestore=function(){return(oa=e.stackRestore=e.asm.Ea).apply(null,arguments)},v=e.stackAlloc=function(){return(v=e.stackAlloc=e.asm.Fa).apply(null,arguments)};e.UTF8ToString=C;e.addRunDependency=$a;e.removeRunDependency=ab;e.FS_createPath=nc;e.FS_createDataFile=ia;
e.FS_createPreloadedFile=sc;e.FS_createLazyFile=qc;e.FS_createDevice=X;e.FS_unlink=ra;e.stackAlloc=v;e.stackSave=ma;e.stackRestore=oa;e.cwrap=function(a,b,c,d){c=c||[];var f=c.every(h=>"number"===h||"boolean"===h);return"string"!==b&&f&&!d?e["_"+a]:function(){return dd(a,b,c,arguments)}};var gd;Za=function hd(){gd||jd();gd||(Za=hd)};
function jd(){function a(){if(!gd&&(gd=!0,e.calledRun=!0,!Ja)){e.noFSInit||lc||(lc=!0,kc(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?X("/dev","stdin",e.stdin):Zb("/dev/tty","/dev/stdin"),e.stdout?X("/dev","stdout",null,e.stdout):Zb("/dev/tty","/dev/stdout"),e.stderr?X("/dev","stderr",null,e.stderr):Zb("/dev/tty1","/dev/stderr"),fc("/dev/stdin",0),fc("/dev/stdout",1),fc("/dev/stderr",1));Ib=!1;gb(Ua);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==
typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Va.unshift(b)}gb(Va)}}if(!(0<Xa)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Wa();gb(Ta);0<Xa||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();jd();


        // The shell-pre.js and emcc-generated code goes above
        return Module;
    }); // The end of the promise being returned

  return initSqlJsPromise;
} // The end of our initSqlJs function

// This bit below is copied almost exactly from what you get when you use the MODULARIZE=1 flag with emcc
// However, we don't want to use the emcc modularization. See shell-pre.js
if (typeof exports === 'object' && typeof module === 'object'){
    module.exports = initSqlJs;
    // This will allow the module to be used in ES6 or CommonJS
    module.exports.default = initSqlJs;
}
else if (typeof define === 'function' && define['amd']) {
    define([], function() { return initSqlJs; });
}
else if (typeof exports === 'object'){
    exports["Module"] = initSqlJs;
}
